### ISSUE TITLE
Add first-person (FPS) demo project

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-demo-projects#1]
First-person 3D games (not just FPSs, but also walking simulators and puzzles like Myst) are very popular, I think it'd be great if there was a first-person demo.

**Comment by spookdogg** [comment]
Some sort of first person controller demo would be HEAVILY appreciated

**Comment by Calinou** [comment]
Such a demo could be part of the 3.0 release (since the renderer is going to change a lot, it is probably not worth starting it right now).

**Comment by paper-pauper** [comment]
How about a demo based on [this](https://github.com/gokudomatic/eco-fps-controller)? Most of the work should be already done.

**Comment by spookdogg** [comment]
@Calinou 
Cool! Thanks for listening!

@paper-pauper 
I think it's best that the Godot team does everything themselves... They know the engine inside and out and all their demos are packed with neat coding tricks you may not have known about.
I'm not slagging off gokudomatic's code quality, I just feel that the Godot team will know more cool tricks with the engine.

**Comment by NathanLovato** [comment]
Done, closing
