### ISSUE TITLE
Port demos to TSCN/TRES format

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-demo-projects#10]
Moved from https://github.com/godotengine/godot/issues/4196:

> The demos are currently using the binary SCN format. Now that TSCN is relatively mature, I think we should switch all demos to it, so that it's easier to spot bugs or regressions in scene files

Done for 2D demos already.

**Comment by HummusSamurai** [comment]
Would you still be interested in doing this for the rest of the demos? (Or will changes be halted till 3.0?)

I'd be applying the [steps described here](https://godotengine.org/qa/2602/a-fast-way-to-convert-scn-scenes-to-new-format).

I started using the Platformer 3D demo for a quick prototype and will be converting it anyway to please git, so might as well do the rest.

**Comment by aaronfranke** [comment]
https://github.com/godotengine/godot-demo-projects/pull/331

**Comment by aaronfranke** [comment]
I'm glad to announce that there are currently zero demos using the `.scn` or `.res` formats!

The next step would be to get rid of binary `.vs` files, but that's not implemented yet so it will have to wait until 4.0+: https://github.com/godotengine/godot/issues/16023
