### ISSUE TITLE
How to download Squash the creeps 3d?

### ISSUE THREAD

**Issue by JouBqa** [godotengine/godot-demo-projects#1017]
Hi, 
I'm not seeing a download button anywhere?

**Comment by Calinou** [comment]
GitHub doesn't provide a built-in way to download individual folders, but you can use this link: https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fgodotengine%2Fgodot-demo-projects%2Ftree%2Fmaster%2F3d%2Fsquash_the_creeps
