### ISSUE TITLE
WARNING: 2D MSAA is not yet supported for GLES3. in Dynamic TileMap Layers Demo due to setting to Compatibility

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot-demo-projects#1028]
The Dynamic TileMap Layers demo has been set to `renderer/rendering_method="gl_compatibility"` however, it is also set to use MSAA 2D 4x (Slow) Anti Aliasing, resulting in this warning on every run:

`WARNING: 2D MSAA is not yet supported for GLES3.`

https://github.com/godotengine/godot-demo-projects/blob/31d1c0c1122717b3ad74aeb94255bc38def52747/2d/dynamic_tilemap_layers/project.godot#L67

Is this the intended behavior?

It seems like the demo should either be set to run in Forward+ by default or MSAA 2D should be turned off to avoid confusing demo users.
```[tasklist]
### Tasks
```

**Comment by Calinou** [comment]
> Is this the intended behavior?

No, I forgot to disable 2D MSAA when switching the demo to the Compatibility rendering method in https://github.com/godotengine/godot-demo-projects/pull/1024. Feel free to open a pull request for this :slightly_smiling_face:
