### ISSUE TITLE
compute/texture demo is broken at current master version of Godot

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot-demo-projects#1031]
**Which demo project is affected:**
compute/texture

**OS/device including version:**
Godot v4.3.dev (29b3d9e9e) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

**Issue description:**
When I opened the project, open the water scene and switch back to main scene, the log spams as this image:

![image](https://github.com/godotengine/godot-demo-projects/assets/8315986/d837ab21-3aa4-43c4-9c84-c27cbb6f9cf1)

```
scene\resources\texture_rd.cpp:90 - Condition "!RD::get_singleton()->texture_is_valid(p_texture_rd_rid)" is true.
servers\rendering\rendering_device.cpp:3991 - Parameter "pipeline" is null.
servers\rendering\rendering_device.cpp:4079 - Parameter "uniform_set" is null.
servers\rendering\rendering_device.cpp:4079 - Parameter "uniform_set" is null.
servers\rendering\rendering_device.cpp:4079 - Parameter "uniform_set" is null.
This compute pipeline requires (0) bytes of push constant data, supplied: (32)
No compute pipeline was set before attempting to draw.
```

Trying to run the project will crash at start:

![image](https://github.com/godotengine/godot-demo-projects/assets/8315986/87e53f20-7748-4eb8-9e1a-4b3a4d272be0)

**Comment by Calinou** [comment]
This is almost certainly an engine issue, since running the project directly doesn't crash. Please report this on godotengine/godot with the backtrace and reproduction project attached.
