### ISSUE TITLE
Does not work as-is in Godot 4.x

### ISSUE THREAD

**Issue by LazarusDS** [godotengine/godot-demo-projects#1046]
**OS/device including version:**

Processor	AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
GPU - NVIDIA GeForce RTX 2070 SUPER Windforce

**Issue description:**

Trying to open the project via the Godot editor tries to get me to convert it somehow so it will work will 4.x, but the message box is so high (even on a 2k monitor) that I cannot close it and have to force Godot to close via the Control Panel. 

I managed to get it open by opening project.godot but it still doesn't work. Everything is coded as it was in 3.x and it just breaks. I tried fixing a few things I know (like onready -> @onready), but I couldn't get it to work.

**Comment by aaronfranke** [comment]
Which project?

**Comment by LazarusDS** [comment]
I'm referring to the Joypads Demo/Tool, which is linked directly in the official Godot docs for "Why doesn't my controller work?"

Here: https://godotengine.org/asset-library/asset/140

**Comment by Calinou** [comment]
The URL in the documentation is outdated – it points to the 3.x version. You want to use https://godotengine.org/asset-library/asset/2785 instead :slightly_smiling_face: 

I'll update URLs in the documentation shortly.
