### ISSUE TITLE
Godot Crashed when opening dodge_the_creeps

### ISSUE THREAD

**Issue by wrzrmzx** [godotengine/godot-demo-projects#1059]
**Which demo project is affected:**

dodge_the_creeps with Godot Engine v4.2.2.stable.official [15073afe3]

**OS/device including version:**

OS: macOS Sonoma 14.5
Device: MacBook Air M1

**Issue description:**

When I tried to open this project, Godot crashed. Other projects can be opened correctly

**Screenshots of issue:**

<img width="1112" alt="截屏2024-05-27 19 18 28" src="https://github.com/godotengine/godot-demo-projects/assets/31785985/b6efef10-e188-40d1-a68d-cdae350130ad">

**Comment by fallax** [comment]
Exact same issue here on a Mac mini M1 - tried checking out a fresh copy of the examples, downloaded the .zip, still the same problem with both of them.

**Comment by hello-josh** [comment]
Same issue running on a MacBook Air with the M3 chip

**Comment by Calinou** [comment]
This is an engine issue that is fixed in 4.3 by https://github.com/godotengine/godot/pull/88816.

Try opening the demo in 4.3.rc2 and it should work 🙂
