### ISSUE TITLE
what mean ^ in ^"xxx"? 

### ISSUE THREAD

**Issue by Heltman** [godotengine/godot-demo-projects#1087]
**Which demo project is affected:**

Dodge the Creeps

**OS/device including version:**

**Issue description:**

Main.md contain contain code:
https://github.com/godotengine/godot-demo-projects/blob/7223aec0012ba5f89b7f9f28a65e91abb30be0cc/2d/dodge_the_creeps/Main.gd#L29

**Screenshots of issue:**

**Comment by aaronfranke** [comment]
That is a NodePath literal. See https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#literals
