### ISSUE TITLE
Flipped tiles in hexamap demo are broken

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-demo-projects#11]
Moved from https://github.com/godotengine/godot/issues/4206:

@akien-mga

> Likely since https://github.com/godotengine/godot/issues/3204 which caused some offset for vertically flipped tiles. As I understand it this PR fixed a previously wrong behaviour, so now we need to rethink the hexamap demo to show how to make hexagonal tilesets that can still be flipped properly.

@neikeq:

> I kind of "fixed" it (not really, read next paragraph) by changing the sprites/tiles offset to the center of the tiles/sprites (which is -64, -64) and changing the TileMap origin to center.

The problem? It's only works with the tile preview, not after placing the tile in the TileMap... I opened an issue about this some time ago: https://github.com/godotengine/godot/issues/3209. I can fix that issue if someone tells me what's the correct result with origin set as center (crossing my fingers for it to be the preview), and then I would check this one again.

**Comment by neikeq** [comment]
I will have a look at it once more. Hopefully this time my mind will be more focused than last time :persevere:

**Comment by neikeq** [comment]
Just to inform, https://github.com/godotengine/godot/issues/3209 is still present. If you check the demo, the preview is displayed in a different position compared to the real position when the tile is placed.
