### ISSUE TITLE
Truck Town Semi-Truck physics wonky when using Godot Jolt physics engine

### ISSUE THREAD

**Issue by BinaryWarlock** [godotengine/godot-demo-projects#1101]
**Which demo project is affected:**
`3d/truck_town`

**OS/device including version:**
Linux

**Issue description:**
When enabling the Godot Jolt addon, the semi-truck vehicle is essentially unplayable: the trailer is moved upwards off the ground at the hinge, and the truck is moved downwards off of its wheels. Might be an issue with the joint.

Works fine with default Godot Physics.

**Screenshots of issue:**

**Comment by Calinou** [comment]
cc @mihe

I'm not sure if this is a Jolt issue, a godot-jolt issue or an issue with how joints are configured in the demo (maybe it was incorrect all along).

**Comment by mihe** [comment]
Yeah, I've seen this one.

The setup in that demo is odd. It relies on the `ConeTwistJoint3D` supporting multiple revolutions, which is not something Jolt supports, and something I haven't bothered to mention in the list of differences with Godot Physics.

I can make a PR to switch it over to a 6DOF joint instead, which I would say is the more intuitive choice for that particular setup.

**Comment by Calinou** [comment]
> I can make a PR to switch it over to a 6DOF joint instead, which I would say is the more intuitive choice for that particular setup.

Yes, please do 🙂

**Comment by mihe** [comment]
@Calinou See #1102.
