### ISSUE TITLE
Add a Bistro Demo

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot-demo-projects#1112]
Adding an [Amazon Lumberyard Bistro](https://developer.nvidia.com/orca/amazon-lumberyard-bistro)  demo project to demonstrate more realistic graphics in the Godot Engine.

**Which demo project is affected:**
There is no.

**Description:**
I suggest adding a demo of Bistro to this repository, since this demo can demonstrate more realistic and modern graphics of the Godot engine, it can demonstrate the maximum capabilities of the engine, especially for 4.3+

This demo is under a free license, so there shouldn't be any problems with this.

I could do a complete porting of the project, adding all the scenes, and adjusting them to different lighting.

But... there is already a ready-made port for this demonstration - https://github.com/Jamsers/Bistro-Demo-Tweaked from Jamsers, we would prefer to port the rest of the scenes and add them to the project, with the permission of Jamsers

**Comment by aaronfranke** [comment]
How many megabytes would that be in total? We don't want to put anything too big in this repo, for example the TPS demo gets its own repo: https://github.com/godotengine/tps-demo So it may be better to keep it in @Jamsers's repo.

However, I asked @WickedInsignia who did the original port, who is currently blocked from the Godot Engine organization, and he said that he is not ok with anyone using his work so long as he is blocked.

So, for both practical and legal reasons, I'm going reject this proposal. Thanks for contributing!

**Comment by JekSun97** [comment]
@aaronfranke  I understand, but I would like to know how official demos or examples are distributed. If I decided to develop my own demo project for the engine's graphics capabilities with cutscenes, what conditions should I follow? or is that out of the question?

**Comment by aaronfranke** [comment]
> I would like to know how official demos or examples are distributed.

The demos are distributed in the Godot Asset Library, which can be downloaded either from the website or within the project manager. You can submit your own project to the Asset Library, without ever touching this repo. https://godotengine.org/asset-library/asset

> If I decided to develop my own demo project for the engine's graphics capabilities with cutscenes, what conditions should I follow?

Something elaborate and with cutscenes is out-of-scope for this repo, it would be too big. I suggest you submit such a project as an asset on the Godot Asset Library under your own name.
