### ISSUE TITLE
(GD Paint) Brush strokes aren't continuous if you move your mouse faster

### ISSUE THREAD

**Issue by cgormaz** [godotengine/godot-demo-projects#1117]
**Which demo project is affected:**
GD Paint Demo 4.2 (https://godotengine.org/asset-library/asset/2768)

**Issue description:**
First of all, this demo is amazing! My only complaint is that if you move your mouse a bit fast, you can see each "circle" instead of a continuous line. While it's not necessary for each circle to be exactly 1px away from each other, it would be great to limit the separation between them a bit, or maybe make it place a new circle more often. I apologize if this is more of a feature request than a bug.

Keep up the amazing work!

**Screenshots of issue:**
![Captura de pantalla 2024-09-30 121311](https://github.com/user-attachments/assets/6c80290e-9c3f-457f-9922-1893d48ce912)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-demo-projects/issues/846.

**Comment by cgormaz** [comment]
Thank you so much for your reply! Have a wonderful day!
