### ISSUE TITLE
Failing to open 2D project

### ISSUE THREAD

**Issue by TaqsBlaze** [godotengine/godot-demo-projects#1121]
**Which demo project is affected:**
2D dodge_the_creeps

**OS/device including version:**
Windows 10

**Issue description:**
When I try to open the project using Godot 3.5.3 it fails to open the project saying it was created using a newer version

**Screenshots of issue:**
https://snipboard.io/0H9Jei.jpg

**Comment by aaronfranke** [comment]
You need to use the 3.x branch of the demos for Godot 3.x: https://github.com/godotengine/godot-demo-projects/tree/3.x

The master branch is for Godot 4.x.
