### ISSUE TITLE
A mismatch between Godot engine's version and projects' sourcecode version in Godot HTML5 demo projects

### ISSUE THREAD

**Issue by ZhongGuangshen** [godotengine/godot-demo-projects#1126]
**Which demo project is affected:**
https://godotengine.github.io/godot-demo-projects/

**OS/device including version:**
HTML5 (tested in Edge130.0.2849.52)
![屏幕截图 2024-10-25 132929](https://github.com/user-attachments/assets/10c8aba4-a096-4882-b8c4-f13f17615127)

**Issue description:**
At present, the Godot engine version in the Godot HTML5 demo project(https://godotengine.github.io/godot-demo-projects/) does not match the Godot version of the demo project source code. The Godot engine version in [the HTML5 demo](https://godotengine.github.io/godot-demo-projects/) is 3.3.3 stable, while the source code for the demo project may be Godot 3.5 or even higher

![屏幕截图 2024-10-25 151615](https://github.com/user-attachments/assets/6833b9b5-bcbc-44eb-8c8c-e57669998516)
In a nutshell, [the current HTML5 demo](https://godotengine.github.io/godot-demo-projects/) is equal to running a project in 3.5 branch (or even higher) using Godot 3.3.3 stable version, **_therefore, errors in HTML5 are inevitable_**

![屏幕截图 2024-10-25 151919](https://github.com/user-attachments/assets/61f1e285-3239-41ed-9b8c-a4b029012793)
**_In addition, I personally think that the statement in Godot demo projects has some issues because in reality, projects in the Master(4.x) cannot be compiled by Godot 3.3.3 stable at all._**

This issue is based on https://github.com/godotengine/godot-demo-projects/issues/1125#issue-2610329475,  and I noticed that a similar problems have been encountered in issue https://github.com/godotengine/godot-demo-projects/issues/786#issue-1428078118, referring to this issue I mainly tested **_the project 2.5D Demo With GDScrpit._** 

In Windows 11, I exported the HTML5 version of 2.5D Demo With GDScrpit under 3.5branch using Godot3.3.3 and used `python-m http.server+ http://localhost:8000` to access it locally in Edge, **_resulting in the same issue of  character‘s being unable to move_** as that in https://godotengine.github.io/godot-demo-projects/misc/2.5d/
![godotweb](https://github.com/user-attachments/assets/948046d8-89dc-446c-b8a3-2eb118870872)
in https://godotengine.github.io/godot-demo-projects/misc/2.5d/ The character in the middle cannot move
![godotloacal](https://github.com/user-attachments/assets/c7a67c2c-6fa4-4ad0-a11e-d472e2a9ed3b)
The characters in the 3.5 branch project exported in stable 3.3.3 version cannot be moved either

**Screenshots of issue:**

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-demo-projects/issues/786.
