### ISSUE TITLE
I need use this plugging for godot 4.3, but since 9 month I wait upgrade of this plugging

### ISSUE THREAD

**Issue by muhal24** [godotengine/godot-demo-projects#1150]
The Google Play Billing version on the Godot official website is 5.2.1, but Google accepts 6.0.1 or higher according to its updated policies.
So I need version 6.0.1 or higher.

**Comment by clayjohn** [comment]
Hi! This repo is for reporting issues with the official Godot demo projects. For issues with the Google Play billing add-on, please open an issue on the repo for the Google Play billing add on https://github.com/godot-sdk-integrations/godot-google-play-billing
