### ISSUE TITLE
Very low FPS in Platformer 3D demo under some circumstances

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-demo-projects#174]
When running the demo and moving to some areas of the demo level, FPS will become very low, even on high-end hardware (tested on an i7-6700K and a GTX 1080, I get 10-15 FPS when it happens).

This may not be due to the renderer, but rather due to a scripting error.

See the console output sent by an user on Discord below:

![godot_platformer](https://user-images.githubusercontent.com/180032/33729463-07bb58e2-db7e-11e7-8233-749c69cd0ef6.png)

**Edit:** Someone on Discord commented that this may be due to the coin animation.

> looks like the low fps issue with the 3d platformer is the coin animation uses 
> `rotation_deg`
> which changed to 
> `rotation_degrees`

**Comment by TwistedTwigleg** [comment]
@Calinou is this fixed now?

I fixed the animation property before running the project and it seems to have fixed the low FPS (for me at least), but I don’t have anything to compare it against. Do you mind testing?

**Comment by NathanLovato** [comment]
I don't have the issue. As the bug dates back from 3.0 beta and there's no update I'm closing this. You can open another issue if need be
