### ISSUE TITLE
Multiplayer game 

### ISSUE THREAD

**Issue by orelvis15** [godotengine/godot-demo-projects#178]
Create example to the multiplayer game.

**Comment by Calinou** [comment]
This is already done, see [Multiplayer Bomber](https://github.com/godotengine/godot-demo-projects/tree/master/networking/multiplayer_bomber) and [Multiplayer Pong](https://github.com/godotengine/godot-demo-projects/tree/master/networking/multiplayer_pong). Note that these are designed for Godot 3.0 only.

**Comment by orelvis15** [comment]
Ho thanks, I had not seen it.
