### ISSUE TITLE
Multiplayer Bomber Parser Error

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot-demo-projects#189]
OS: Ubuntu Linux 16.04
Godot version: latest (master branch)
Godot Demo Projects version: latest (master branch)

The Multiplayer bomber doesn't run.

Output:
```
Parser Error: Name for argument 'name' can't shadow class property of the same name.
0 - res://gamestate.gd:59
```

It ran a week ago with the same code so I don't know if the demo should be updated or if it's an Engine's issue.

**Comment by vnen** [comment]
This was caused by godotengine/godot#15611, now Node expose `name` as a property.

**Comment by LinuxUserGD** [comment]
Ok, renaming it from name to namespace or something else works

**Comment by LinuxUserGD** [comment]
[multiplayer_bomber.zip](https://github.com/godotengine/godot-demo-projects/files/1628425/multiplayer_bomber.zip)
