### ISSUE TITLE
( demo submission proposal ) Fur shading demo

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot-demo-projects#19]
Ok, as I don't want to struggle with GIT to submit a PR, i will just give you a link to the demo here and will let you include/PR/Gitify it if you like :

https://github.com/SuperUserNameMan/GodotFurShaderDemo/

![Screenshot](https://github.com/SuperUserNameMan/GodotFurShaderDemo/raw/master/fur_shading_demo/screenshot.png?raw=true)

**Comment by vnen** [comment]
This seems more like AssetLib material. Demo projects should be just for showing basic functions of the engine and there's already a shader demo.

**Comment by SuperUserNameMan** [comment]
oh yep, i forgot about the Aassetlib.
Maybe i'll to submit there then.

**Comment by reduz** [comment]
Demos will be moved to assetlib soon (discouraging the zip download)

**Comment by Calinou** [comment]
Closing, as this is out of scope for the official demo projects repository. The [asset library](https://godotengine.org/asset-library) is a better place to host this kind of demos.
