### ISSUE TITLE
Sensor Example crashes on android 7.1.2

### ISSUE THREAD

**Issue by alex9099** [godotengine/godot-demo-projects#193]
Hi, i was trying the Sensor example but it crashed on android 7.1.2, is there any permission that i should mark?

**Comment by Calinou** [comment]
Can anyone reproduce this on Godot 3.1.2 or [Godot 3.2 beta5](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-5)?

**Comment by aaronfranke** [comment]
Closing this has abandoned, feel free to comment and this can be re-opened.
