### ISSUE TITLE
Demo for 3D raycasting

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-demo-projects#2]
Moved from https://github.com/godotengine/godot/issues/892

@M4N1AC

> Please make an example showing how to use 3D raycasting, and camera.project_ray_

@TheoXD

> I'm probably superlate, but try this http://blenderstars.com/uploads/tmp/Click.zip if you're still looking for a solution.

**Comment by Calinou** [comment]
I suppose this demo could take the form of a few visual effects:

- Lens flare that hides when occluded by something
- Laser coming from the bottom of the screen that bounces on surfaces?
