### ISSUE TITLE
Isometric demo is broken

### ISSUE THREAD

**Issue by reduz** [godotengine/godot-demo-projects#200]
Y-Sort not working because tiles are not drawn from the center. At some point this probably changed and broke isometric.

**Comment by Hinsbart** [comment]
Related issues on main repo: https://github.com/godotengine/godot/issues/13062 / https://github.com/godotengine/godot/issues/15249

**Comment by reduz** [comment]
There is not much secret to this, if origin of the tile is not at the center, isometric does not work.

**Comment by reduz** [comment]
This used to work fine, it would be interesting to know which changes broke it and why.

**Comment by MarianoGnu** [comment]
related PR: https://github.com/godotengine/godot/pull/13216

**Comment by shayneoneill** [comment]
Is the current (3.0.0 stable) demo still the broken one?  Because its *definately* clipping in all the wrong ways, and I've tried all sorts of things and I cant convince it to behave correctly either. 

I'm not sure I understand why this is closed?

**Comment by akien-mga** [comment]
It works fine for me: 
![image](https://user-images.githubusercontent.com/4701338/37089146-e791ed6a-21ff-11e8-91b9-226a2d720fe6.png)

The version of the demo [on the Asset Lib](https://godotengine.org/asset-library/asset/112) is also the fixed one: https://github.com/godotengine/godot-demo-projects/tree/3.0-d69cc10/2d/isometric

**Comment by shayneoneill** [comment]
Hmm. Ok. Just grabbed the latest and it appears I am mistaken.  My apologies. 
Not to work out what I'm doing wrong in my project.
(Once I figure out why AnimatedSprite doesnt work when its in a sub-scene)
