### ISSUE TITLE
Ear rape in Platformer 3D demo

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot-demo-projects#202]
Godot 3.0 RC1 - Windows 10

This issue was reported to me by @viniciuskps (our audio specialist).
For some reason, the audio is bugging (ear rape warning) because of reverb effects in audio buses.

Removing all reverb resources and creating new ones fixed it.
I'm not sure why this is happening, but it was working in the beta.

(I can't open a PR because my pc is dead and I'm using a potato laptop)

**Comment by vnen** [comment]
I just noticed this, didn't know there was an open issue. I don't know exactly when things changed (my git-blame-fu is failing), but this can be solved by setting the reverb feedback property to something lower than 1.
