### ISSUE TITLE
2D Platformer RigidBody - seesaw not working

### ISSUE THREAD

**Issue by carlosfvieira** [godotengine/godot-demo-projects#208]
Version: 3.0-d69cc10
Godot Engine: 3.0 stable

![image](https://user-images.githubusercontent.com/8830610/35618315-88a27c64-0672-11e8-9ee4-d7f15e8a58dc.png)

**Comment by akien-mga** [comment]
It's just in temporary maintenance, but the handyman is procrastinating fixing it.

**Comment by Zadck** [comment]
Little more info: This seems to extend to all PinJoint2D's on all RigidBody2D's set in either Rigid or Character mode. Not just this seesaw; creating any RigidBody2D and trying to pin it results in it just falling down (they stay up of course in Static or Kinematic mode).

**Comment by pwab** [comment]
@Zadck actually the problem with the seesaw can be solved quite simply:

![seesaw](https://user-images.githubusercontent.com/19271185/36635371-fb5e7c40-19b3-11e8-8d2c-40fd718b7ccf.png)

**Comment by Zadck** [comment]
@pwab Two things:
1. This works but is not a clean workaround as it requires a second RigidBody2D to be made. Using, say, the sprite as the Node B entry does not constrain it.
2. In 2.1, it was not necessary to define the Node B entry and it could instead simply pin to a fixed location in space. You can see this in 2.1 demo project, where the Seesaw only has the Node A defined. It would appear that this is still intended to still be the case going off of this documentation here: http://docs.godotengine.org/en/3.0/classes/class_pinjoint2d.html .

**Comment by pwab** [comment]
1)
> Node B needs to be filled in with another RigidBody2D, and this clutters up scenes.
I can not see how a second PhysicsBody (StaticBody2D would fit better here than a RigidBody2D) clutters up a scene. Can you explain why you think it does?

2)
> In 2.1, it was not necessary to define the Node B entry for a PinJoint2D and it could instead simply pin to a fixed location in space.

This seems to be a breaking change between 2.1 and 3.0. I ran into this problem [here](https://github.com/godotengine/godot/issues/13448). There might be some missing documentation about that.

> It would appear that this is still intended to still be the case in 3.0, going off of this documentation here: http://docs.godotengine.org/en/3.0/classes/class_pinjoint2d.html . It currently is not the case.

Thanks for pointing this out. It seems this page is **outdated**. You can see that it definitly can't work that way in the docs for the parent class: [Joint2D](http://docs.godotengine.org/en/3.0/classes/class_joint2d.html#member-variables)

> NodePath node_a - The first body attached to the joint. **Must derive from PhysicsBody2D**.
> NodePath node_b - The second body attached to the joint. **Must derive from PhysicsBody2D**.

**Comment by aaronfranke** [comment]
This issue doesn't exist anymore on the current version of this demo.
