### ISSUE TITLE
3D platformer texture artefacts

### ISSUE THREAD

**Issue by danboid** [godotengine/godot-demo-projects#209]
I have tried the 3D platformer demo under godot 3.0 / Ubuntu 17.10 running on a Intel HD4600 (Haswell) GPU and there are lots of grey lines between the textured tiles, as you can see in the screenshot.

![artefacts](https://user-images.githubusercontent.com/1429783/35673377-4db2bb60-0739-11e8-9c14-ae90e9f818e3.png)

**Comment by bojidar-bg** [comment]
Note that those lines come from the texture:
![](https://cdn.pbrd.co/images/H5BFEob.png)

**Comment by danboid** [comment]
The wall texture has the same prob it seems?

**Comment by TwistedTwigleg** [comment]
Yeah. It seems the last vertical line of pixels on the far right is missing in the tile texture.
