### ISSUE TITLE
New Demo: IK Demo

### ISSUE THREAD

**Issue by TwistedTwigleg** [godotengine/godot-demo-projects#211]
I have been working on a relatively simple IK (inverse kinematics) system for Godot 3, intended to be used in the FPS tutorial I'm making. Now that the system is fairly stable, I thinking about maybe sharing the system here on the demo repository.

The IK system works both in the editor and at runtime, the performance is pretty good (though it could use some touching up in a few places), and the demo would add IK implementation for others to use and build on. The code could also help as a reference on how to make a EditorPlugin that reacts when exported variables are set and can show how to add nodes to the scene tree (at runtime and in the editor).

You can see the system in action [here](https://www.youtube.com/watch?v=TfAO2W6lO8E), [here](https://www.youtube.com/watch?v=RwouEFDMelM&feature=youtu.be), and [here](https://www.youtube.com/watch?v=mGRH9M3FLis).

I can add a few examples to show how to use the system (like dynamically placing feet on terrain. Another potential use case that I'd like to look into is making ragdolls)

I can also write a tutorial in the docs explaining how the system works. It's fairly simple and should be relatively easy for intermediate Godot users to understand.

What do you guys think?

**Comment by pwab** [comment]
This would be totally awesome! I already saw your nice work and hoped you would share 😄 

I saw that your system works in 3D space. Is it based on the [skeleton node](https://godot.readthedocs.io/en/3.0/classes/class_skeleton.html)? How about using constraints? Would it be possible to get it working in 2D space too?

I am asking because I was working on an IK system too but only for 2D space. It is based on the [FABRIK algorithm by Andreas Aristidou](http://andreasaristidou.com/FABRIK.html) and although this approach is intended to be used in 3D I was only interested in using it for some 2D models. Constraints still do not work as wanted because of deadlock situations but I'm sure I will get this working somehow.

If your system would work with 2D models too I am interested how it compares in complexity and performance. And if not I could add my 2D implementation as another demo.

**Comment by TwistedTwigleg** [comment]
Thanks pwab! 😃 

My system uses a look-at-IK solver to calculate the rotations in 3D space. I use the skeleton node to get the bone transforms, do the some calculations, and then send the transform back. Currently the system is built around the skeleton node, but thinking about it the system should (in theory) be able to work with any node that has a look_at function with some slight modifications.

Currently I do not have a constraint system in place. I have a relatively good on idea on what I need to do, but of course that generally means it's going to be harder than I think.

That's cool that you are working on an IK system too! I couldn't wrap my head around translating the algorithms I found into code, so I just used the look-at-IK solver because I understood how it worked. That's really neat that you're using a tried and true algorithm! I'd love to see it in action!

My system only works in 3D space currently, though it shouldn't be too hard to translate into 2D. That said, I wasn't planning on adding a 2D implementation, mostly because I primarily work in 3D and rarely use 2D 😆. If you want, I can see about making it work in 2D, or I can just leave it and we can use your (likely better) system for a 2D example.

Regardless I'd be happy to compare our implementations! I found working on the IK system to be really fun, and I've learned (and still am learning) a lot of interesting math as I've gone along.

**Comment by pwab** [comment]
Well okay then I think we could try to add two demos for now: one with your implementation concerning 3D space and one with a 2D implementation. After that we can try to unite both - if feasible and reasonable.

I have to say that my implementation is just a plain script file (not a plugin) but it could be possible to work on that too. I will not have much time the next days/weeks but if I find the time I will prepare a PR. Here are just some first impressions:

**Unconstrained**
![unconstrained](https://user-images.githubusercontent.com/19271185/35769774-94447374-0910-11e8-941f-b444262f05b6.gif)

**Constrained**
(You can clearly see the deadlock situation where the IK chain can't get constructed even if the target is in reach.)
![constrained](https://user-images.githubusercontent.com/19271185/35769778-98bdfb1e-0910-11e8-9f5c-0535aa0a3efc.gif)

**Comment by TwistedTwigleg** [comment]
Sounds good! Having two different demos adds more variety too!

I have to say: WOW! Your system looks really good! (Totally blows mine out of the water 😆). I'm also having some trouble working around a couple deadlock situations in my version too (with multi bone IK chains), so you're not alone there.

I wouldn't worry about making it a plugin if you don't want to. I've just made my a plugin in an effort to reuse it for the FPS tutorial. Also, no worries on the wait! Take your time, I don't mind waiting (and my apologizes if I made you feel pressured)

**Comment by pwab** [comment]
> [...] and my apologizes if I made you feel pressured

No worries. This encourages me even more! :)

Thanks to a recent [twitter post](https://twitter.com/reduzio/status/958305883976536064) by reduz I got some assets to test my system with sprites (cutout) instead of polygons. Works great too but I will have to place the sprites pivot points by the script itself.

**Godette Test** 
![godette](https://user-images.githubusercontent.com/19271185/35828945-9a55ee8e-0ac1-11e8-8184-fc160b26aef6.gif)

(Assets and License can be found in the [godot-design](https://github.com/godotengine/godot-design) repository)

**Comment by TwistedTwigleg** [comment]
Nice! It looks like it works well with Godette (that's her name right?). I wish you luck! placing pivots in GDScript sounds like it could get interesting.

____

Unfortunately a couple days ago I found I had a huge bug: My IK system didn't work with anything but a skeleton at origin with no rotation applied. Thankfully I've managed to fix the look-at-IK side of things (mainly it's just converting from skeleton space to global space) but I still have an annoying global rotation bug with my IK chain.

After that, I'll have to see if differing scales brakes things or not... 😦 (At least it shouldn't be too hard to fix, in theory).

I don't want to release something that only works in one very specific scenario, so I guess it's going to take a little longer than I hoped to release a demo. If all goes well, I'll have the bug(s) fixed this week, and then can clean up the code and get a demo made shortly after.

**Comment by pwab** [comment]
> Hopefully I can start working on the IK demo soon [...]

It seems you found some time to create some impressive stuff [here](https://www.youtube.com/watch?v=C5fNj9GhyFA). Congrats on successfully implementing FABRIK for your IK-Chains :+1: 

At the moment I can't spare any time for working on the 2D version as well. I also want to wait a little bit how the new [Skeleton2D stuff](https://github.com/godotengine/godot/commit/7cd867c3fe48187dced1060dedb22cc82f5aa094#diff-e2bc749d06f87e77ee1a2a55816a0777) is implemented. Maybe that will supersede my implementation of constructing virtual bones.

**Comment by TwistedTwigleg** [comment]
> Congrats on successfully implementing FABRIK for your IK-Chains

Thanks! Everything seems to be working, and it even works with skeletons moved and/or rotated from origin. I tried add constraints, but I couldn't get it working, but for my uses I don't really need it. I'm probably going to skip constraints for now and maybe add it later.

I decided to try using FABRIK since your IK implementation uses it. After reading FABRIK from several sources, [this Roblox](http://wiki.roblox.com/index.php?title=Inverse_kinematics) one was probably the best of the ones I found, and my implementation is heavily based on it.

Knowing that it was at least possible for 2D gave me the inspiration to try and use it for 3D. So, thanks! :+1:  I likely wouldn't have a working bone chain without your post!

> At the moment I can't spare any time for working on the 2D version as well. I also want to wait a little bit how the new Skeleton2D stuff is implemented. Maybe that will supersede my implementation of constructing virtual bones.

Sounds good, and take all the time you need!

Hopefully the Skeleton2D stuff will work similarly to Skeleton, but without some of the quirks. (For example: `get_bone_global_pose` returns a transform for the bone in the skeleton's global space, not world space.). I took a look through it and it looks like it is similar, so who knows?

**Comment by TwistedTwigleg** [comment]
Alright, I've finished the plugin, made some examples, and now it's ready to be made into a PR!

Where should I put it?
The demo has a plugin adding two nodes (`IK_LookAt` and `IK_FABRIK`), with a examples folder containing a few examples showing how the plugin works. I'm leaning towards putting it in 3D, since it's a neat feature to have, but technically the demo is more of a plugin...

Thoughts?

**Comment by pwab** [comment]
Putting the demo into 3D seems fine. You could also provide an extra repository for the plugin itself.

**Comment by TwistedTwigleg** [comment]
Okay. Thanks!
