### ISSUE TITLE
IAP demo isn't working !

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot-demo-projects#212]
IAP demo is showing singleton error

**Comment by akien-mga** [comment]
More details would be nice...

**Comment by gamergamesz** [comment]
sorry for the less info, i thought godotpaymentV3 is gone so i was just confirming it.  
win10, i7, 960m   


![screenshot 181](https://user-images.githubusercontent.com/13883739/35700465-11de0268-07b9-11e8-8864-3676d66b0809.png)

![screenshot 182](https://user-images.githubusercontent.com/13883739/35700464-1141024c-07b9-11e8-82b6-0eb7533f94a9.png)

**Comment by akien-mga** [comment]
You should use `Engine.get_singleton()` instead: http://docs.godotengine.org/en/latest/classes/class_engine.html#class-engine-get-singleton

**Comment by gamergamesz** [comment]
Iam using IAP demo but when i hit f6 it gives me this error "nonexistent function 'get singleton' in 'project setting'"

**Comment by gamergamesz** [comment]
thank you very much it is working now!!! time to close this issue
