### ISSUE TITLE
RigidBody2D's not constrained by PinJoint2D's as in 3.0 as in 2.1

### ISSUE THREAD

**Issue by Zadck** [godotengine/godot-demo-projects#221]
PinJoint2D's on all RigidBody2D's set in either Rigid or Character mode in all projects in 3.0 would seem to be doing nothing. The RigidBody2D node is not constrained, and simply falls. (They stay up of course in Static or Kinematic mode).

As @pwab pointed out, setting node_b to another RigidBody2D will still create a working joint. However, in 2.1, it was not necessary to define the node_b to another RigidBody2D to make them function. It would now seem to be mandatory, and I can find no documentation on this--and the 3.0 documentation that exists says a PinJoint2D can "pin a single body to a fixed position in space" ( http://docs.godotengine.org/en/3.0/classes/class_pinjoint2d.html )so I assume it is a bug.

This has been documented indirectly here: https://github.com/godotengine/godot-demo-projects/issues/208 However, after further testing, the scope of this issue seems to be well-beyond just that one demo project and so I felt it merited a separate issue report as it is not about just fixing that one demo's seesaw--if this is considered clutter, feel free to remove it.

**Comment by pwab** [comment]
By _"all projects in 3.0"_ - which projects do you mean exactly? (Despite from the one discussed in the linked issue)

> The RigidBody2D node is not constrained, and simply falls.

A RigidBody is not constrained only by using a PinJoint and set its `node_a`-property to the RigidBodys path. It needs another PhysicsBody (`node_b`) which this pin is related to. If you want to constrain a RigidBody at a specific position in the world you have to pin it to a StaticBody.

Sorry if I misunderstood your issue description but I can't see the problem here - apart from the seesaw of the Dynamic Character Controller demo.

**Comment by Zadck** [comment]
@pwab 
You seem to have also replied in the referenced issue posting, so I will reply here and hopefully conversation can be kept here on this to prevent confusion.

All projects, you can create a project from scratch with basic assets and see that PinJoint2D's are not working as they did in 2.1.

A second RigidBody2D set as the Node B works but is not a clean workaround as it requires a second RigidBody2D to be made. Using, say, the sprite as the Node B entry does not constrain it. Node B needs to be filled in with another RigidBody2D, and this clutters up scenes.

In 2.1, it was not necessary to define the Node B entry for a PinJoint2D and it could instead simply pin to a fixed location in space. You can see this in 2.1 demo project, where the Seesaw only has the Node A defined. It would appear that this is still intended to still be the case in 3.0, going off of this documentation here: http://docs.godotengine.org/en/3.0/classes/class_pinjoint2d.html . It currently is not the case.

**Comment by pwab** [comment]
Well I was answering in the other issue. See my comment there. I think this is not related to the demo repository but instead should be adressed in the docs repo.

There is an [open issue](https://github.com/godotengine/godot-docs/issues/537) about migrating from 2.1 to 3.0. This tutorial could include breaking changes like these.

**Comment by pwab** [comment]
> [...] 3.0 documentation says that SpringJoint2D's can pin a single body to a fixed position in space, and they can no longer do so. 

For further discussion: https://github.com/godotengine/godot-docs/issues/1180

**Comment by pwab** [comment]
> [...] 3.0 documentation says that SpringJoint2D's can pin a single body to a fixed position in space, and they can no longer do so. 

For further discussion: https://github.com/godotengine/godot-docs/issues/1180

**Comment by LinuxUserGD** [comment]
Is it fixed?

**Comment by pwab** [comment]
It was partly fixed:

- The docs were made clear
- The seesaw in the demo wasn't touched yet but there is a separate issue about that

Unless there are no other passages in the docs telling PinJoints only need one anchor node this issue can be closed.

**Comment by Calinou** [comment]
I'll close this issue as it has been superseded by #208.
