### ISSUE TITLE
2D rubegoldberg demo is broken in 2.1.5 beta 2

### ISSUE THREAD

**Issue by wombatstampede** [godotengine/godot-demo-projects#227]
The behaviour of joints has changed in 2.1.5 beta2 which breaks the rubegoldberg demo.

The pendulums are "attached to the background" in godot 2.1.4 and earlier whereas they are falling down in version 2.1.5.

The reason is that "joint wall" in pendulum.tscn is has no link for "Node B" which worked in versions prior 2.1.5.

The demo can be made functional again by adding a StaticBody2D and linking "Node B" in "joint wall" to it.

**Comment by akien-mga** [comment]
CC @RandomShaper

**Comment by RandomShaper** [comment]
https://github.com/godotengine/godot/pull/17678 should take care of this.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/17678.
