### ISSUE TITLE
Can't import in 2.1.4

### ISSUE THREAD

**Issue by fedeb95** [godotengine/godot-demo-projects#229]
I'm using version 2.1.4 in Godot and couldn't import any of this projects. I also searched in the downloads on the website but only found projects for godot 3. Anyway, here in the README should be clear how to import this projects

**Comment by akien-mga** [comment]
You should use the `2.1` branch: https://github.com/godotengine/godot-demo-projects/tree/2.1

**Comment by fedeb95** [comment]
Will try that version, thank you

**Comment by akien-mga** [comment]
"Fixed" by #231.
