### ISSUE TITLE
Error in Multiplayer Bomber

### ISSUE THREAD

**Issue by songproducer** [godotengine/godot-demo-projects#23]
Parser Error: Unexpected token: Identifier:remote

Line 57 in GameState.gd:
`remote` func register_player(id, name):

**Comment by mefihl** [comment]
You use Godot 2.1 ? For new multiplayer code, you need use Godot 2.2 alpha.

**Comment by akien-mga** [comment]
Same as #21, use the 2.1 branch if you're using 2.1-stable, the master contains new demos that work only in 2.2.

**Comment by songproducer** [comment]
How can I get 2.2 alpha? Do I need to compile?

**Comment by Calinou** [comment]
> How can I get 2.2 alpha? Do I need to compile?

Usually, yes, although you can acquire a community-produced nightly build such as from [here](https://github.com/Calinou/awesome-godot#unofficial-builds-of-godot).

**Comment by songproducer** [comment]
Thanks Calinou that's a great resource!
