### ISSUE TITLE
Astar demo project

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-demo-projects#235]
I've seen a few questions about pathfinding, got a few requests for tutorials already. That's why I updated the nav2d demo yesterday. 

For any kind of grid-based pathfinding you'd better use Astar. Godot's implementation is very flexible but could use a complete example.

If that's okay I'll work on this today, in a demo that uses Astar and a tilemap node for 2d navigation.

Should it be a new Astar demo or part of the existing navigation one?

**Comment by akien-mga** [comment]
I think a new Astar demo would be great :)
