### ISSUE TITLE
Multiplayer Tag

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot-demo-projects#239]
We might benefit from having a Multiplayer tag on demo projects that have multiplayer functionality. This would make search and filtering a bit easier, when looking for specific examples of multiplayer games.

This could and probably should also be used for other asset submissions that include multiplayer functionality. :)

**Comment by bojidar-bg** [comment]
Related: https://github.com/godotengine/godot-asset-library/issues/108.
We still don't have tags in the assetlibrary.

**Comment by Calinou** [comment]
Closing, as this is not related to the demo projects repository.

For the record, the upcoming asset library rewrite features a tags system very similar to GitHub topics.
