### ISSUE TITLE
Platformer tiles lighting is really dark on device

### ISSUE THREAD

**Issue by songproducer** [godotengine/godot-demo-projects#24]
It seems the textures aren't loading correctly on Android, but are on Desktop.
The textures for the floor don't load at all when running on device.

texture.tex
tiles.scn
robotrigged.scn
enemy.scn
coin.scn
bullet.scn
all show red crosses in the filesystem panel.

Hovering over the red crosses shows that

/platassets/texture.png
/platassets/tiles.dae
/platassets/robotrigged.dae
/platassets/enemy.dae
/platassets/coin.dae
/platassets/bullet.dae

files are missing

There is no platassets folder in the project directory.

**Comment by songproducer** [comment]
/platassets/texture.png
/platassets/tiles.dae
/platassets/robotrigged.dae
/platassets/enemy.dae
/platassets/coin.dae
/platassets/bullet.dae

files are missing

**Comment by songproducer** [comment]
Fixed!

1. Created folder platassets in project
2. Opened tiles.xcf in Gimp and exported to platassets/texture.png
3. Reimported it to texture.tex

**Comment by aaronfranke** [comment]
This issue is so old that I doubt it's still relevant. If you are still experiencing issues, we can re-open this, or you can open a new issue, but for now I'll close this issue.
