### ISSUE TITLE
Platform 3D bot model file

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot-demo-projects#242]
I would like to add animation to the bot in the platformer 3d demo. However I can't do that without its 3d model file. Do you think I can have access to such file? Preferably .blend

**Comment by aaronfranke** [comment]
@reduz Do you still have the original model?

@SIsilicon You could also consider using the robot model in the TPS demo. It's much more detailed.

**Comment by SIsilicon** [comment]
@aaronfranke I could, but I want to work with this demo and its rendition of "Gobot" here.

Also I eventually figured out how to sort of export the model to blender. But it's not very elegant.

**Comment by Calinou** [comment]
I doubt reduz still has access to the `.blend` sources for the older 3D demos. This should probably be closed.

PS: In the future, we should require all 3D demos to include `.blend` sources to avoid issues like this :slightly_smiling_face:

**Comment by SIsilicon** [comment]
Good idea! The source files can be put in there own `src` folder with a `.gdignore` file inside too.

**Comment by aaronfranke** [comment]
That part isn't necessary, since Godot already won't import `.blend` files.

**Comment by SIsilicon** [comment]
True, but won't the `src` folder itself still show up in the Godot file manager without the gdignore?

**Comment by aaronfranke** [comment]
I would expect `blend` files to be stored alongside their imported versions, such as `dae` or `glb`.

**Comment by SIsilicon** [comment]
I guess different people have different ways of sorting their files. I personally would put source files in a source folder, and the assets they produce in another folder.
