### ISSUE TITLE
Rename Drag and Drop demo?

### ISSUE THREAD

**Issue by johnnygossdev** [godotengine/godot-demo-projects#243]
Hello!

I was looking at the drag & drop demo and it seems to primarily be a `ColorPickerButton` demo. 

![color picker example](https://user-images.githubusercontent.com/3285214/38793133-201664ec-417a-11e8-963b-5f6ed02e8d42.gif)

It shows that the `ColorPickerButton` can be used for some very specific drag and drop action but the demo shows no logic to create a custom object that can be dragged around.

The demo is still useful but perhaps the name is a bit misleading as I expected to see how objects could be manipulated and moved about the screen using the mouse.

I'm currently working on a drag and drop example which moves "cards" around the screen. It basically moves a sprite around and uses simple functions such as `lerp()` to make the movement look nicer. It might also be a good introduction to such functions for beginners.

![00 movement](https://user-images.githubusercontent.com/3285214/38793436-7f0b69c4-417b-11e8-918d-4fdfd801e502.gif)

If you like, I can clean it up and add it as a demo too.

Cheers!

**Comment by pwab** [comment]
Thanks for your suggestion. I always thought this demo was kind of weird. :sweat_smile: 

> I'm currently working on a drag and drop example which moves "cards" around the screen. It basically moves a sprite around and uses simple functions such as lerp() to make the movement look nicer. It might also be a good introduction to such functions for beginners.

Your animation looks super cool. It would be awesome if you would share your work!

**Comment by eska014** [comment]
The system used in the demo can be used for drag&drop in general, not just colors. You can display any Control node you want as drag preview using `set_drag_preview()`

**Comment by jaggygames** [comment]
That's good to know! That makes a bit more sense! I still think a rename would be appropriate. Perhaps to Drag & Drop Preview or something similar.

**Comment by aaronfranke** [comment]
I would appreciate further feedback on this. Not sure what to rename it to, or if it even needs a rename anymore. The current name is "Drag & Drop (GUI)" which excludes the possibility of it being [this](https://user-images.githubusercontent.com/3285214/38793436-7f0b69c4-417b-11e8-918d-4fdfd801e502.gif).

I'm not sure that "Drag & Drop Preview" is an improvement - while it makes sense after seeing the demo, I don't think it actually helps people understand what the demo is before opening it (a preview of an upcoming drag-and-drop feature?).

**Comment by johnnygossdev** [comment]
I think "Drag & Drop (GUI)" is a fine name! It's been a while but I think the name got changed along the way.
