### ISSUE TITLE
Request: add normal, specular, etc. maps to the 2d sprite shaders demo (Im attaching assets with godette)

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot-demo-projects#244]
Hello @jaggygames , I just saw that the 2d sprites shaders demo was ported by you, so in case you could I decided to ask...

Im attaching a zip that contains the godette_body.png at full res and cleaned to have transparency, and all the maps that Sprite DLight create at its default settings, depth, normal, occlusion and specular, in case somebody can create a new demo for advanced 2D materials.

[godette_body_material.zip](https://github.com/godotengine/godot-demo-projects/files/1926879/godette_body_material.zip)

Thanks in advance
Best regards

**Comment by jaggygames** [comment]
Hello!

I'm not too familiar with using normals and such but I'll have a look. Perhaps someone else would be better suited to those examples!

Either way I'll update the sprites in the 2D Shader demo to higher resolutions this weekend. I know it was mentioned in #237 to have sharper sprites at least. Thank you!

**Comment by rubenjavier** [comment]
Thanks mate, really appreciated
Im not really sure where else to ask for an example of the 2D version of normal and specular mapping in godot 3.x, I've tried on reddit and discord before, but usually got the answer that is really easy but no examples. with normal and specular would be enough for most people to understand how to do all kind of 2D lightning

**Comment by JarLowrey** [comment]
Normal mapping seems to a bit buggy right now - https://github.com/godotengine/godot/issues/18299

**Comment by jaggygames** [comment]
@rubenjavier 

I had a look at the files and there are some artifacts around the edges. Do you happen to have a copy without them to hand? 😄 

![godotte](https://user-images.githubusercontent.com/3285214/39026936-c87e5aa2-4479-11e8-8ac0-6405e4d2f6e2.PNG)

**Comment by rubenjavier** [comment]
Sorry, I just got the original Image from godot that came without transparency and added tha alpha channel / cleaned with the magic wand in gimp the best I could, I dont think there is an original done with transparency and cleaned, I'll take a look later at home and clean as much as I can from the borders

**Comment by aaronfranke** [comment]
@rubenjavier Any update? Is this feature still desired?

**Comment by Calinou** [comment]
Note that the Vulkan renderer supports specular lighting in 2D out of the box.

**Comment by Megamega53** [comment]
@johnnygossdev 
I've cleaned up the white artifacts from the albedo png file. Here is a zip file that contains a transparent version, one with green backgrounds and another with a black background.






[godette_body_albedo clean.zip](https://github.com/godotengine/godot-demo-projects/files/4412717/godette_body_albedo.clean.zip)

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-demo-projects/pull/511. Specular mapping will be added when the demos are upgraded to Godot 4.0.
