### ISSUE TITLE
Many filenames on the IK demo are UPPERCASE in the code but actually lowercase and compile fail

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot-demo-projects#245]
@TwistedTwigleg Hello,
Some filenames / directory names are written in uppercase inside the code, maybe this was developed under windows and worked, but on any nix O.S. compilation fails, this are some of the files I encountered (sorry I didnt wrote down every error that appeared until compilation was succesful)

inside fabrik_ik.tscn:
Target_From_MousePos.gd
Button_Change_Scene.gd
addons/SADE/IK_FABRIK.gd
addons/SADE/IK_FABRIK.png

inside look_at_ik.tscn:
Target_From_MousePos.gd
Button_Change_Scene.gd

inside fps_example.tscn:
Button_Change_Scene.gd
addons/SADE/IK_FABRIK.gd
addons/SADE/IK_FABRIK.png

**Comment by TwistedTwigleg** [comment]
I wondered if changing the file/directory names in Windows was going to cause issues. Changing from upper case to lower case did all sorts of weird things to Git, so I’m guessing this is reminents of that.

Thanks for letting me know! I’ll see about getting a fix for this soon! (I’ll use Ubuntu to make sure it all works. Also, no worries about not writing it all down)
