### ISSUE TITLE
Hex demo tiles are offset

### ISSUE THREAD

**Issue by lifelike** [godotengine/godot-demo-projects#248]
Not sure if this is a bug in Godot 3 or the Hexagonal Map Demo, but hex tiles are placed offset to the low-right of where the cursor actually is when placing tiles. This is visible with the ghost tile that follows the cursor around as well. If tiles are rotated or mirrored they jump around as if rotated around the center of the cursor, ending up offset in other directions.

3.0.2.stable.custom_build.2ff3b08
Debian 9.3
Intel(R) HD Graphics 400 (Braswell)

**Comment by vsiles** [comment]
I got the same kind of issue while trying to learn how to do hexagonal tiles in godot (see [here](https://godotengine.org/qa/31715/detect-tile-under-mouse-cursor?show=31791#c31791)).
In the example project, the tiles are hexagonal, but the underlying grid is still square/rectangular, so we can't do much here if we want to "pick" a tile: get_cell is quite broken. Are there some plan to improve hexagonal support ?

**Comment by bojidar-bg** [comment]
Does this happen on 3.1 as well? If it does, please open an issue on the [godotengine/godot](https://github.com/godotengine/godot) repository.

**Comment by vsiles** [comment]
> Does this happen on 3.1 as well? If it does, please open an issue on the godotengine/godot repository.
Sorry I was on holiday. Can I download 3.1 directly or do I have to build a version from github ? I only see 3.0.6 on godotengine.org

**Comment by vsiles** [comment]
I compiled godot from github source base and the same behavior is showing. I'll open the issue there then.

**Comment by zhengying** [comment]
Is there a workaround for this bug ?

**Comment by Calinou** [comment]
This was fixed in https://github.com/godotengine/godot-demo-projects/commit/1ca3204e0ac0f209d5df5167e20df72c024d51f9, closing.
