### ISSUE TITLE
Reorganize demos to work closer to the manual?

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-demo-projects#251]
Now the manual is better organized I feel like we could improve the demos' structure a little bit too, for clarity. Some ideas just to get the conversation stated:

1. there's still a `misc` folder that has a bit of everything. Can we split it to fit the tutorials category of the docs?
2. how about moving physics demos to a top-level `physics` folder? Both 2d and 3d. Have `physics/2d` and `physics/3d` if the demo count goes up a lot, or rename all 2d physics demos `2d_*` so they're grouped together?
3. Is `mono` clear to everyone? Is `C#` not an option? Mono being a compiler I'm not sure everyone would get it.
4. having C# and visual script at the root makes it so they're spread apart and surrounded by GDscript examples. What do you think of `scripting_languages/c#` ?

Current tutorials/ category list in the manual for ref:

![image](https://user-images.githubusercontent.com/12694995/39161921-e824f690-47ad-11e8-84fc-906e0f3961bd.png)

**Comment by aaronfranke** [comment]
1. I recently moved the loading demos to their own folder. Any other categories we could make? Keep in mind that we have 0 demos for some of those documentation categories, and some categories don't really make sense to have demos for (like math).

2. I don't think this would be an improvement. Some demos use physics but aren't physics demos.

3. It's called the Mono module, and the download page mentions Mono version, so I think it's clear enough.

4. I don't think it's necessary. We also don't need every project to have a C# version, so there will always be far fewer C# demos as long as GDScript exists. So I think it's good as-is.

**Comment by NathanLovato** [comment]
It seems I had missed your reply, sorry about that!
