### ISSUE TITLE
I think we should improve First Person 3d examples

### ISSUE THREAD

**Issue by Logmytech** [godotengine/godot-demo-projects#256]
I'm a beginner. Have not done much Game Dev, especially because most Engines don't have good Linux support.

Godot is awesome, but I think we should polish up the examples.

Unreal has really good FPS and TP examples.

The Kinematic 3d example is aweful. Disco lights make me get a vomity feeling and others too might not find it very good.
The controls are just awful. The box slides like it's on ice instead of acting like a decent controllable character.

Even the platformer controls are too slidy, slow etc

**Comment by vnen** [comment]
There's a new TPS demo on the way.

**Comment by TwistedTwigleg** [comment]
For the FPS demo, we could add the finished project from the [FPS tutorial](http://docs.godotengine.org/en/latest/tutorials/3d/fps_tutorial/part_six.html).
(though it's a tad large, so maybe not?)

**Comment by Logmytech** [comment]
We should definitely add stuff from the tuts.

The tut parts seem to be better than the examples.

And I would recommend not having horrible lighting choices like Violet.
I have nausea problems and the violet light in the example make me very nauseating.

Also, I think the controls of all examples like 2d and 3d platformers be like Super Mario 64 instead of the horrible control we have now.

In the beginning I thought Godot was bad because of the bad controls in examples.

**Comment by Zireael07** [comment]
The violet light can indeed be nauseating (not for me personally) and above all, it looks really ugly.

The person above says that the default Godot 3.0 lighting is fine re: nausea, so a fix could be as easy as having the default world environment?

**Comment by Logmytech** [comment]
We need pleasant neutral/natural lightning.

For example this one.

https://i.imgur.com/YVvKysl.png

**Comment by Zeph-dev** [comment]
There is the FPS demo/template project here https://github.com/TwistedTwigleg/Godot_FPS_Tutorial from the tutorial on the Godot docs. Should help you to learn the engine if you look at the finished product, then do the tutorial here http://docs.godotengine.org/en/3.0/tutorials/3d/fps_tutorial/index.html to see how it's made, and make it yourself. Hope this helped ;)

**Comment by aaronfranke** [comment]
I changed the title to only mention first-person examples because we already have the TPS demo which is a fantastic demo that showcases third-person very well, and then there's also the 3D platformer and the 3D kinematic character demo, so I think this is solved for third-person.

**Comment by Anyeos** [comment]
I made a FPS that is still incomplete (but it is actually working on Godot 3.2.1) and someone can use it to fork a new one. It have "decent" graphics as I expect from a real FPS game. 
It is incomplete and don't have a tutorial, so it is more suitable to make a fork and create a tutorial based on that instead of sending pull requests. Because I have no time to improve it for now.

Check it at https://github.com/Anyeos/Godot-PFPS-ejemplo
