### ISSUE TITLE
Turn-based combat/RPG demo

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-demo-projects#263]
We're working on a turn-based RPG tutorial series with @henriiquecampos.

Henrique made a JRPG demo already, just wanted to give everyone a heads-up! 

![discord_2018-07-02_10-38-59](https://user-images.githubusercontent.com/12694995/42141438-305f725c-7de4-11e8-90dc-96c32fd7420d.png)

I think it was requested on Patreon, so that would answer the patrons' request. Also, it's different from #61 as the other issue mentions it's not about combat.

Right now the little demo includes:

1. Top-down grid-based movement (a little like RPG maker)
2. A simple dialogue system
3. Transition in and out of combat
4. Turn-based combat

**Comment by henriiquecampos** [comment]
Hey, thanks a lot for the heads-up! 

Just passing by to leave a small showcase .gif of it :blue_heart:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10171059/42184075-8aad870e-7e1a-11e8-9548-30c6b39f3c02.gif)

It shows quite useful approaches to these system, specially for combat as it uses `PackedScene` to instantiate the combat actors, so is very simple to design a combat :smile:

**Comment by jaggygames** [comment]
Wow this is amazing! Thank you!

**Comment by Zeph-dev** [comment]
That looks great! Really looking forward to it, do you think this could be modified to act like a Pokémon-like game? That would be really cool!

**Comment by henriiquecampos** [comment]
@Zeph-dev Pokémon was the reference actually, so yeah, totally :smile:

**Comment by jaggygames** [comment]
@Zeph-dev Any ETA on this? :heart_eyes:

**Comment by henriiquecampos** [comment]
@jaggygames well it's up to the guys managing the repo :thinking: it is as shown in the gif, but the code may need tweaks to keep it as standard as the other demos. So it will depend on:

1. If and when it will be accepted
1. The time between the PR and reviewing it
1. The amount of changes it will take to make it acceptable (lots lol)
1. Me applying said changes :stuck_out_tongue:

**Comment by Zeph-dev** [comment]
@henriiquecampos awesome!

**Comment by Zeph-dev** [comment]
@henriiquecampos so can you have more than one character to fight with, or be able to switch between characters? It would be awesome for that to happen because then people can make Pokémon fan-games, or their own JRPGs. It's awesome to see what you've done already, hope you continue it.

**Comment by henriiquecampos** [comment]
@Zeph-dev no :D I didn't think about team swap ;-; 

To add this feature I'd need to rework some of the systems, as for now it doesn't support a Party system (multiple playable actors).

**Comment by jaggygames** [comment]
@henriiquecampos I'd love to play around with it - do you have the PR so I can take a looky? I can't see it here ^_^

**Comment by NathanLovato** [comment]
> So it will depend on:
>    If and when it will be accepted
>    The time between the PR and reviewing it

I'm part of the reviewers, already looked at some of the code. just ping me when you submit it

**Comment by Zeph-dev** [comment]
Ah ok then @henriiquecampos hopefully we could potentially do a re-write of the code so it supports team swap and party systems. It would be awesome if that was the case, even though it would probably take a bit of time to do.

TIA,
Zeph

**Comment by henriiquecampos** [comment]
OK, PR is up as #267 let's the code nightmares and smells begin!

**Comment by Zeph-dev** [comment]
OK! Hope it goes well! :)

**Comment by ronroniv** [comment]
Awesome! Looking forward to tinkering with this 😉

(Maybe a quibble for a demo that is not about UI, I think color scheme of buttons could be better. Text on buttons (especially inactive ones) are not quite readable and the active button could be more apparent imo.)

**Comment by LikeLakers2** [comment]
In my personal opinion, the yellow used for the buttons in this demo is really bright, in a distracting sort of way. It also makes it hard to read any text placed atop it.

Additionally, I'm noticing that this demo doesn't work properly on 3.1-alpha.

I also feel like it's too organized at times (why do you need a new folder for one or two files?).
