### ISSUE TITLE
C++ examples

### ISSUE THREAD

**Issue by baptx** [godotengine/godot-demo-projects#271]
It would be nice if there are C++ examples as a demo like it is done for GDScript and C#.
For example, the platformer 3D demo written entirely in C++ would be interesting to compare the code.
At the moment, it looks like Godot is mainly focused on C#: https://github.com/godotengine/godot-docs/issues/140

**Comment by aaronfranke** [comment]
GDNative (C and C++) demos now have their own dedicated repo: https://github.com/godotengine/gdnative-demos/

Note that the repo is currently fairly unmaintained (as is GDNative itself), but that is now the place to find C++ demos.
