### ISSUE TITLE
Observer from Window Managment extends from Spatial not KinematicBody

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot-demo-projects#272]
Observer in misc\window_management\observer\observer.tscn is KinematicBody but in observer.gd it extends Spatial so this demo can't start

**Comment by aaronfranke** [comment]
Actually, it can work just fine. A KinematicBody node can have a Spatial script, but not vice versa, a Spatial node can't have a KinematicBody script. So it's not a bug.

Regardless, this was changed in https://github.com/godotengine/godot-demo-projects/commit/77f7afaba4f666311c7078fa92298c5e3f2c91a1#diff-0b82c7e84373634e029d0c016e8765b1
