### ISSUE TITLE
Particle Systems example - Emit_Mask doesn't work.

### ISSUE THREAD

**Issue by Kolrath** [godotengine/godot-demo-projects#276]
Godot Build / Version - "Godot Engine v3.0.6 Stable Official"
OS - Windows 10

Regarding Example - 2d_particles ("Particle Systems")

Issue: The Emit_Mask particle system does work correctly.

When you first import the example the Emit_Mask will show as working correctly in the editor window.

When you run the program the Emit_Mask doesn't show up. I'm assuming its either not visible, not emitting correctly, or outside of the program windows bounds.

If you close out of Godot, then re-launch Godot and re-load the "Particle Systems" example you'll get a different, though still broken, result.
In the editor the Emit_Mask will immediately show as a closely packed together "plus sign", as if the particle emitters are all heavily focused in that one area, and its location will move, visibly,  up a good bit and somewhat to the left.

Running the program is the same as before. The Emit_Mask doesn't show as working anywhere in the window.

Closing Godot, re-launching Godot, and re-loading the "Particle Systems" remain the same as it was after the initial closing and re-launching. Emit_Mask doesn't show as working even in the editor and it doesn't work when the program is run.

I hope this information is helpful.

**Comment by aaronfranke** [comment]
It works fine for me in Godot 3.2.1. Closing.
