### ISSUE TITLE
State Machine Example - Player floats if Staggered while Jumping.

### ISSUE THREAD

**Issue by Kolrath** [godotengine/godot-demo-projects#278]
Godot Build / Version - "Godot Engine v3.0.6 Stable Official"
OS - Windows 10

Regarding Example - finite_state_machine ("Hierarchical State Machine example")

Issue: If the Player is currently in the Jumping state and they become Staggered they halt all movement and just float there till the Stagger ends.

Maybe this is intended as the Stagger state prevents movement input, but it just looks out of place. Not really a bug, but more of a professional polish thing in my eyes.

It seems like it would be more fitting for the Player to have the momentum of their Jump halted, but to still be affected by gravity and fall down. Alternatively, maybe just have their ability to change direction their Jump prevent and continue on with their initial momentum.

**Comment by NathanLovato** [comment]
That's intended - and also wanted behavior depending on the game (e.g. in fighting games it's common to freeze the character mid-air when it takes a hit)
