### ISSUE TITLE
State Machine Example - Program glitch and crash if you Attack while Staggered

### ISSUE THREAD

**Issue by Kolrath** [godotengine/godot-demo-projects#279]
Godot Build / Version - "Godot Engine v3.0.6 Stable Official"
OS - Windows 10

Regarding Example - finite_state_machine ("Hierarchical State Machine example")

Issue: Program glitches out and then crashes if you Attack while Staggered

If the Player is in the Staggered state and they then attempt to Attack the program will glitch out.

The Player sprite will no longer flash red, but instead show as brown / yellow.

The Attack animation will play fully, but when it ends the program will crash out.

The debugger "Stack Frames" indicates these scripts and lines...
stagger.gd - Line 14 - 
`	assert anim_name == "stagger"`
state_machine.gd - Line 55 - 
`	current_state._on_animation_finished(anim_name)`

**Comment by NathanLovato** [comment]
Should be fixed with the last FSM patch - just forgot to mention this issue in the PR. Thanks for the report!
