### ISSUE TITLE
Bézier curves demo proposal

### ISSUE THREAD

**Issue by JohnMeadow1** [godotengine/godot-demo-projects#295]
I have noticed we have Bézier curves request on Patreon demo voting. 
I have made this interactive examples for teaching purposes:
Godot 2.1.5
https://github.com/JohnMeadow1/GodotGeometryElements/tree/master/final/bezier_curve
https://github.com/JohnMeadow1/Bezier-Painting

Godot 3.0 - rough conversion form 2.1.5
https://github.com/JohnMeadow1/GodotGeometryElements/tree/master/godot_3/final/bezier_curve

![bezier](https://github.com/JohnMeadow1/GodotGeometryElements/raw/master/assets/examples_animations/bezier.gif)
It covers linear, quadric and cubic curves

Maybe we can convert it to meet official demo standards?

**Comment by Xrayez** [comment]
The demonstration is neat, I'd personally refactor the code to have three distinct curves, which would be shaped based on how many points they have as children, the algo would pick respective equations then.

**Comment by Xrayez** [comment]
On the other hand, there's `Curve2D` resource which help to deal with bezier curves specifically, and there's a general lack of documentation on this: godotengine/godot#29437.

**Comment by JohnMeadow1** [comment]
@Xrayez chave you seen this?:
https://docs.godotengine.org/en/3.1/tutorials/math/beziers_and_curves.html

**Comment by Xrayez** [comment]
Oh yeah somehow I forgot to mention this, this tutorial was recently added. I guess the official demo should reflect it then.

**Comment by aaronfranke** [comment]
@JohnMeadow1 @Xrayez Would y'all like to implement this? I think it would be nice to have.

Would it make sense to integrate this into the Tween demo?

If you are not sure about the official demo standards, the PR template has a list of some requirements, and also you can look at the existing demo projects.

**Comment by JohnMeadow1** [comment]
Can you link me to PR template I do not know where to look for it.
I would love to add some of my project, and recently I have a bit more time to work on them, so might as well try to do it according to a template.

**Comment by aaronfranke** [comment]
https://raw.githubusercontent.com/godotengine/godot-demo-projects/master/.github/PULL_REQUEST_TEMPLATE.md

Make sure that if you add any projects, they are simple and either demonstrate engine features or demonstrate how specific mechanics can be implemented.

**Comment by aaronfranke** [comment]
Closing this issue because it is not actionable as-is. If this is desired, feel free to make a PR, considering the above comments.
