### ISSUE TITLE
Demos for tool mode usage

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-demo-projects#3]

**Comment by kubecz3k** [comment]
Any idea how that demo could work? Something very simple like reaction on export var getter setter?

**Comment by aaronfranke** [comment]
Perhaps @willnationsdev could help with this.

**Comment by aaronfranke** [comment]
The following demos in the repo currently contain tool scripts:

* 3D IK demo.

* Custom node, material creator, and material import plugin demos.

* Dynamic split screen demo.

* Matrix transform demo.

* Both of the 2.5D demos.

I think these demos have plenty of good examples of how to use tool scripts, and I don't think having a demo with only an empty "Hello World"-style tool script would be useful. So, closing.
