### ISSUE TITLE
render gles 2.0 is not working

### ISSUE THREAD

**Issue by IuryBorges1993** [godotengine/godot-demo-projects#303]
render gles 2.0 is not working, please verifying.

**Comment by Calinou** [comment]
Currently, all projects are designed to be used with the GLES3 renderer. I guess it would make sense to convert the less graphically-intensive ones to GLES2 (so that they run on more devices), and keep the rest on GLES3.

**Comment by aaronfranke** [comment]
Fixed by #426, all projects that can use GLES 2 without affecting visual quality now use GLES 2. Any demo with particles, and almost all 3D demos, still use GLES 3.
