### ISSUE TITLE
Port VisualScript demos to 3.1

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-demo-projects#308]
Workflow:
    * Open the demo
    * Load and save all scenes
    * Run, check and fix warnings/errors

It doesn't seem trivial for VS, there are errors that I'm not familiar with (cc @fire).

**Comment by fire** [comment]
Are we able to get a list of the errors, I'll see what I can later today after work hours.

**Comment by t-karcher** [comment]
@fire : When trying to run the "circle pop" demo, this error comes up immediately after starting the script:
![Circle_Pop_Error_in_V3 1](https://user-images.githubusercontent.com/22897030/58891384-acbd4600-86ec-11e9-9df3-95492f1c93eb.PNG)
("Invalid index property name" in the "Get size" node)

I tried to find similar error reports, but the closest I could find was https://github.com/godotengine/godot/issues/26740 , which is not really comparable, but at least shows the same error in a "get" node....

**Comment by fire** [comment]
I would suggest recomposing x and y into a vector2. I'm not sure why it's exposed as seperate x and y variables rather than a vector .

**Comment by fire** [comment]
Where's "circle pop" demo?

**Comment by t-karcher** [comment]
https://github.com/godotengine/godot-demo-projects/tree/master/visual_script/circle_pop

**Comment by t-karcher** [comment]
Recomposing doesn't help:
![image](https://user-images.githubusercontent.com/22897030/58893859-3707a900-86f1-11e9-9aac-cccf59d41678.png)
(Same error message in same node)

**Comment by fire** [comment]
Grabbing 3.1 from steam and see what happens. Normally I would try on master, but this is a 3.1 thread.

**Comment by fire** [comment]
![vs_308](https://user-images.githubusercontent.com/32321/58895478-d785ab00-86a8-11e9-9a7d-eef7e5f3ff0e.PNG)

These fixes made it work.

Notice I made a sequence and did the initialization there.

**Comment by t-karcher** [comment]
I still wonder how this worked until 3.0, but thanks anyway! Will you submit your changes to the repo, or should I do it?

**Comment by fire** [comment]
Can you do it? I don't know the demos too well.
