### ISSUE TITLE
Platformer Demo: Space Inbetween Tiles Flickering

### ISSUE THREAD

**Issue by spookdogg** [godotengine/godot-demo-projects#32]
Version 2.1
Latest demos for zip download on site
Platformer demo

The space in between the tiles is visible for brief moments when the screen moves a lot (you can see it flickering by simply jumping around for a bit, falling a long distance helps)

Problem appears to be that mipmaps are used to process the tilesheet image, turning them off seems to remove the effect

getting errors that say
"iCCP: known incorrect sRGB profile"
May be related?

**Comment by akien-mga** [comment]
> getting errors that say
"iCCP: known incorrect sRGB profile"
May be related?

That one is not related, it's a harmless (but noisy) libpng warning.

**Comment by spookdogg** [comment]
>That one is not related, it's a harmless (but noisy) libpng warning.

Ah, thanks... 
(as you can tell, I'm not the most well versed in the source code)

**Comment by Calinou** [comment]
Closing, as this was probably fixed a while ago.
