### ISSUE TITLE
navigation demo character doesn't quite reach destination

### ISSUE THREAD

**Issue by blain1972** [godotengine/godot-demo-projects#321]
in the [navigation demo](https://github.com/godotengine/godot-demo-projects/tree/master/2d/navigation) the character doesn't quite reach its destination.

This can be seen by adding

`print('$Character.position ', $Character.position, ' last_point ', last_point)`

to the `move_along_path()` function, **within the `for loop` and after** `path.remove(0)`

You'll see the character is always a few pixels short of the destination.
I would expect `$Character.position` to match `last_point` exactly, or am I missing something?

**Comment by blain1972** [comment]
Right, I initially kludged it with:

```
if $Character.position != last_point:
	$Character.position = last_point
```

but that caused problems when `CHARACTER_SPEED` was set to a higher value.

So, instead I looked for a solution that would use linear interpolation.

```
if distance > distance_between_points and distance_between_points != 0.0:
	$Character.position = last_point.linear_interpolate(path[0], 1.0)
	break
```
The above resolves the issue (inserted between the `if` and `elif`). But, I'm not sure what value to use for `t` in `linear_interpolate(path[0], t)`.

@akien-mga, @NathanLovato 

Any suggestions?

**Comment by bojidar-bg** [comment]
I think it was meant to be like this:
```gdscript
func move_along_path(distance):
	var last_point = $Character.position
	for _index in range(path.size()):
		var distance_between_points = last_point.distance_to(path[0])
		# the position to move to falls between two points
		if distance <= distance_between_points:
			$Character.position = last_point.linear_interpolate(path[0], distance / distance_between_points)
			return
		distance -= distance_between_points
		last_point = path[0]
		path.remove(0)
	# the character reached the end of the path
	$Character.position = last_point
	set_process(false)
```

**Comment by blain1972** [comment]
Wow, that's a lot simpler than my solution. 

That also fixes the `elif` which is never processed.

Only other thing required is

```
func _ready():
	# run _process only when character is navigating the path
	set_process(false)
```

**Comment by bojidar-bg** [comment]
@blain1972 well, that's not really required, since it will just hit `set_process(false)` immediately after running `move_along_path` with an empty path.

**Comment by blain1972** [comment]
Oh, OK. I found when running the older code it was running `_process` all the time, but of course that was in the `elif`...

Thanks :)
