### ISSUE TITLE
Why is "export_presets.cfg" in the gitignore?

### ISSUE THREAD

**Issue by greenfox1505** [godotengine/godot-demo-projects#329]
I've been using this .gitignore for most of my projects. I'm writing a build automation script when I realized this file was the source of some of my issues.

I understand this file was likely writen before GodotHeadless was relevant. Should these lines still be here for projects that automate builds?

Reviewing the formatting of the file has a line called `export_path=...`, and this line seems to be an absolute path, that might need to be adjusted to be relative path. Otherwise I see no reason to exclude this from a project repo.

https://github.com/godotengine/godot-demo-projects/blob/b9bca132215b4f8cd72473d3c85ba87f755cd169/.gitignore#L3

**Comment by Calinou** [comment]
See the discussion in https://github.com/github/gitignore/pull/2827. In short, we need to move sensitive credentials such as the Android keystore to a separate file that can be added to `.gitignore`, and remove `export_presets.cfg` from `.gitignore`.

**Comment by greenfox1505** [comment]
So `export_presets.cfg` will be removed from `.gitignore` at when it no longer has sensitive data in it?

I've only ever built for Windows, Linux, and HTML5, so I don't have any sensitive data in my projects.

What is `export.cfg`? I've only ever seen `export_presets.cfg` in my projects. Is that an old name?

**Comment by Calinou** [comment]
@greenfox1505 I believe `export.cfg` is the file name that was used before Godot 3.0. In Godot 3.0 or later, it's `export_presets.cfg`.

**Comment by Xrayez** [comment]
Note that you can [encrypt your scripts](http://docs.godotengine.org/en/latest/development/compiling/compiling_with_script_encryption_key.html) now again in 3.1, so `export_presets.cfg` may surely have sensitive data regardless of platform, also see godotengine/godot#24582.

**Comment by greenfox1505** [comment]
If that is the case, those encryption keys do not belong in `export_presets.cfg`. A git repo should not contain such sensitive information.

https://www.freecodecamp.org/news/how-to-securely-store-api-keys-4ff3ea19ebda/

**Comment by aaronfranke** [comment]
In addition to keys, my `export_presets.cfg` file contains absolute file paths specific to my own computer. If I move onto another computer, the paths are not relevant anymore. These should not be committed, perhaps they should go in `.import/`.

    export_filter=""
    export_path="/home/aaronfranke/workspace/whatever"
    patch_list=PoolStringArray(  )

**Comment by Calinou** [comment]
Export paths should now be relative as of https://github.com/godotengine/godot/pull/28701. Maybe you need to clear export paths and set them again with a recent build?

**Comment by aaronfranke** [comment]
I've been thinking about this recently, even if there is no direct harm in having such files committed, I think it would not make much sense to have them in the demo projects repo.

Should every project get export presets? If so, what platforms? Would each project have presets for different platforms? What export settings should we use? It would be very easy to have this become inconsistent between each of the demo projects.

When it comes to a gitignore file used in other projects, as @greenfox1505 reports in his first sentence, that is its own discussion and would involve changing [this file](https://github.com/github/gitignore/blob/master/Godot.gitignore).

If that file is changed to not include `export_presets.cfg`, then perhaps we could make the file in this repo have a separate section called `# Demo projects repository-specific` or similar, and we can exclude `export_presets.cfg` only here?

**Comment by Calinou** [comment]
@aaronfranke I think it makes sense to avoid committing `export_presets.cfg` in demo projects indeed.

**Comment by aaronfranke** [comment]
I'm closing this, with the resolution as stated above.

For changing [this file](https://github.com/github/gitignore/blob/master/Godot.gitignore), that's another discussion for another place.

**Comment by Flash1232** [comment]
So what should people that would like to use CI builds do? Can we specify a stripped `export_presets_ci.cfg` such that Godot will take this instead of having to check in the original file containing sensitive data?

**Comment by Calinou** [comment]
> So what should people that would like to use CI builds do? Can we specify a stripped export_presets_ci.cfg such that Godot on the build runner will take this instead of having to check in the original file containing sensitive data?

Not yet, you'll have to wait until https://github.com/godotengine/godot/pull/35930 is merged.

In the meantime, use `sed` to fill in `export_presets.cfg` with secrets in your CI job.

**Comment by Flash1232** [comment]
@Calinou Thanks for the reference! I find [this example](https://github.com/dbrova15/godot-ci-android-bakz/blob/f243a98f1a1277fb03c1bc931875a485e4d6a7a1/.gitlab-ci.yml#L53) very helpful for the time being but as we just want to build for code review, we just copied our `export_presets.cfg` and called it `export_presets_ci.cfg`, committed it to Git and added a `before_script` entry in the `.gitlab-ci.yml`:
```yaml
...

before_script:
  ...
  - cp export_presets_ci.cfg export_presets.cfg
...
```

Looking forward to the PR merge. :)
