### ISSUE TITLE
Get the demo projects into the Asset Library

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-demo-projects#33]
In my opinion users should be able to easily download these demos via the Project Manager > Templates directly from Godot, since downloading them manually is a bit counterintuitive and many users probably don't know these demos exist at all.

**Comment by vnen** [comment]
Well, that is the idea since the Asset Library started. The hard thing is that AssetLib expects one project per repository and here the projects are all together. So it would need to split this or make an exception for the official demos.

**Comment by paper-pauper** [comment]
@vnen I say split them, I think that if someone needs to quickly check out how to implement HDR he probably doesn't need all the other demos as well (and it'd be a waste of bandwidth, too).

I can understand that it's convenient to have all the demos in the same GitHub repository, though. What about:

1. Making a separate repo for each demo
2. Including the repositories as submodules for this git repo (godotengine/godot-demo-projects)

I think this would solve both problems.

**Comment by vnen** [comment]
The only problem with submodules is that updating them is quite a hassle. But the demos are not updated often anyway. And I believe a comment in the Readme file informing to add the `--recursive` flag when cloning is enough.

I think this would be a good step forward for 3. If the plans go right we will have:

* Every demo project available in the Asset Library.
* An Export Template Manager to download and install different versions directly in-editor.

This would also remove the need to bundle everything in the Steam version.

WDYT @akien-mga?

**Comment by akien-mga** [comment]
I'm not particularly looking forward to have to maintain 59 separate git repositories + one to bind them all with ugly submodules. Also by doing so, we'd prevent people from proposing new demos via pull requests - they'd have to ask us directly to upstream their repository.

And when there are file format changes in 3.0, I'd prefer to do all in one or a few commits than to have to handle 59 repos separately again + submit manually 59 updates to the assetlib.

No, the solution is to develop a custom facility to the assetlib that will let us bypass our self-imposed limitation. @bojidar-bg Ideas?

Also, I do agree that having the possibility to install demos separately is good, but at the same time, I think we should continue distributing as a bundle for those who prefer that. Personally I wouldn't want to have to install manually 59 demos through the assetlib to be able to see what the official demos offer for learning material.

**Comment by vnen** [comment]
BTW, how hard it is to rely on GitHub Webhooks? Maybe we could make something with it to update the demos in the AssetLib every time there's a new commit (making zips for every demo), so it wouldn't need to be manually done.

**Comment by paper-pauper** [comment]
> Personally I wouldn't want to have to install manually 59 demos through the assetlib to be able to see what the official demos offer for learning material.

You are right about that, so a "demo pack" option should be provided indeed :+1: 

@akien-mga I understand that maintaining so many repos might be stressful. I think that generating AssetLib packages from the repo automatically and syncing them like @vnen said might be a better idea. WebHooks seems easy enough (it fires a POST event with some JSON at the specified URL), although I believe the same functionality could be achieved with Bash, cron and simple `git pull` without relying on third-party APIs.

**Comment by bojidar-bg** [comment]
Well, we might somehow "hack" the assetlib to fit our needs anyway -- as long as we can get the zips seperatelly...

**Comment by akien-mga** [comment]
We can probably use the GitHub API (not premade URL, but the REST API) to generate archives for subfolders of a repo. At least with GitLab it's possible AFAIK (so worst case we could use a GitLab mirror for that).

**Comment by paper-pauper** [comment]
@akien-mga What's wrong about using a Bash script like this instead (and maybe setting up cron to run it once in a while)? (thanks to [these](http://unix.stackexchange.com/questions/46796/how-to-pass-a-variable-to-an-sh-child-process) [posts](http://stackoverflow.com/questions/15627446/find-and-basename-not-playing-nicely) for making up for my Bash noobery :roll_eyes:)

```bash
#!/usr/bin/env sh
# MIT License

TEMP_DIR="/tmp/godot-demo-projects"
export DESTINATION="./godot-demo-projects"

mkdir -p "$DESTINATION"
git clone https://github.com/godotengine/godot-demo-projects/ "$TEMP_DIR"
find "$TEMP_DIR" -mindepth 2 -maxdepth 2 ! -path '*.git*' -type d -exec sh -c 'zip -r -j ./$DESTINATION/$(basename {}).zip {}' \;
rm -rf "$TEMP_DIR"
```

**Comment by aaronfranke** [comment]
Isn't this solved already? There is a "Templates" tab in the project manager.

**Comment by Calinou** [comment]
@aaronfranke Indeed, demos can be viewed by filtering with the **Official** support level on the [asset library](https://godotengine.org/asset-library).
