### ISSUE TITLE
Replace _input(event) with _unhandled_input(event)

### ISSUE THREAD

**Issue by DagobertDev** [godotengine/godot-demo-projects#344]
_input(event) should be replaced with _unhandled_input(event), which is superior because it allows the use of buttons and other GUI without influencing gameplay.

**Comment by akien-mga** [comment]
Where?...

**Comment by DagobertDev** [comment]
I found one here https://github.com/godotengine/godot-demo-projects/blob/c2d2718cca8f63b7f07a094553d356f736b81dca/3d/navmesh/navmesh.gd#L69
but there are probably others too. Are there any guidlines where this could be added?

**Comment by golddotasksquestions** [comment]
I've been wondering this a long time, maybe you can help me understand @DagobertDev : What would a usecase look like where you have Input that is supposed to control gameplay, however only if is has not been "used up" by GUI?

**Comment by travisryte** [comment]
https://godotengine.org/qa/12831/can-anyone-explain-to-me-unhandled-input-and-handled-input

@golddotasksquestions, Control nodes use _gui_input, I assume, which is a lower priority than _input. We assume that control nodes should take priority, lets say, when using spacebar to select something, we wouldn't want the character to jump. Hence if we use _input, we would not be able to select something in the ui.
