### ISSUE TITLE
2D rendering glitchy

### ISSUE THREAD

**Issue by sparkskapil** [godotengine/godot-demo-projects#346]
I created a 2D pong game with Godot 3.1 on Ubuntu
The ball movement seems glitchy sometimes.

Can anyone tell me what did I do wrong?

Code for the game:
https://github.com/sparkskapil/Pong-Game

**Comment by akien-mga** [comment]
GitHub is not the place for user support, and this repo even less, as it's focused on official demos.

See https://godotengine.org/community for other community platforms, especially the Q&A, Discord, Reddit, Facebook or the forums where people can help you debug the issue.
