### ISSUE TITLE
Gui_in_3D Demo Proposed Fix for Translations

### ISSUE THREAD

**Issue by neoxid501** [godotengine/godot-demo-projects#347]
Hello there!

I had used the Gui_in_3D demo as a template for my menus to avoid raycasting and for the most part I didn't have an issue with it.

However, when I attempted to use a VSlider in the Viewport I noticed a couple of issues that the slider was jittering between it's max and min height. I had instanced the scene into another, and checked the source scene where it functioned normally, but for whatever reason dragging in the y axis is reversed like it would be on a tablet (dragging the mouse down makes the scroll bar go up and vice versa).

I realized that the issue was caused when the scene is taken away from the origin point. Essentially, it seems that the code is not accounting for the possibility that the user may want to move the instance of the GUI away from the origin in the scene.

After a lot of experimenting and several print statements, I got it to work. Here is my proposed fixed:

```
	# the click pos is not zero, then use it to convert from 3D space to area space
	if click_pos.x != 0 or click_pos.y != 0 or click_pos.z != 0:
		pos *= click_pos
		last_click_pos = click_pos - translation # 30
	else:
		# Otherwise, we have a motion event and need to use our last click pos
		# and move it according to the relative position of the event.
		# NOTE: this is not an exact 1-1 conversion, but it's pretty close
		pos *= last_click_pos
		if event is InputEventMouseMotion or event is InputEventScreenDrag:
			pos.x += event.relative.x / viewport.size.x + translation.x # 37
			pos.y += -event.relative.y / viewport.size.y + translation.y # 38
			last_click_pos = pos
```

Specifically I've only changed lines 30, 37, and 38.
This fixes the issue by just adding and subtracting the translation where needed, and I also negated the value being added to `pos.y` to fix the reversed vertical scrolling issue.

Sorry if there's an easier way to propose a change such as this, but I normally don't contribute to public repositories.

edit: Silly me, I forgot the other part of transformations... the rotation. I guess the initial issue I raised was *just* for translations, but when I find a solution to also account for rotations I'll make another edit.

**Comment by aaronfranke** [comment]
Is this issue still relevant? The demo has been significantly changed since this issue was opened.
