### ISSUE TITLE
How can I make my demos available on this repo?

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-demo-projects#349]
Hello, I'm a godot user since 2.1 and I have several finished small projects I could share here, filled with my own art, music and stuff, and wonder if there's a way I can upload them to the official godot demo repo.

**Comment by Feniks-Gaming** [comment]
You need to submit them via pull request. Here is a good guide https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940

**Comment by aaronfranke** [comment]
In addition to submitting a pull request, you should make sure that the demo project you are submitting is meaningful in some way. For example, it could show off some feature of Godot, or it could show how you would implement a certain game mechanic in Godot.

**Comment by aaronfranke** [comment]
In addition to my above comment, I've written a small checklist as part of the PR template: https://raw.githubusercontent.com/godotengine/godot-demo-projects/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by aaronfranke** [comment]
I don't think there's much further discussion to be done here, so I'm closing this issue.

Read the PR template and the other demos to figure out if something would be appropriate for this repository.

Anything does not fit here should go on the Godot Asset Library: https://godotengine.org/asset-library/asset
