### ISSUE TITLE
Viewport capture is not working on iOS 12.1 iPhone s5 device

### ISSUE THREAD

**Issue by danielkotzer** [godotengine/godot-demo-projects#354]
Hi,
I took the code for Viewport image capturing from your script, but didn't work for me on Godot 3.1.1 the official version when I export it to iOS 12 iPhone S5 device, is there something I'm doing wrong?

**Comment by Calinou** [comment]
I'll close this as this is an engine issue: https://github.com/godotengine/godot/issues/32361
