### ISSUE TITLE
Mic record demo isn't working

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot-demo-projects#359]
I just tried the [mic_record](https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record) demo and it doesn't work in my setup. I tried to change the audio driver, but it doesn't work still.

I'm using Solus 4.0 Gnome 3.34.1, Godot points that there are 3 audio drivers:
1. PulseAudio (the demo default)
1. ALSA
1. Dummy

None worked, I'm trying to record the laptop built-in mic, which makes me think: isn't there a way to select the mic which you are going to record from?

Anyway, it would be nice to know how to fix that

**Comment by CombustibleLemonade** [comment]
@Calinou I tried this on a windows 10 laptop, and it worked perfectly. It seems to be a Linux issue.

**Comment by Calinou** [comment]
I'll close this, as this is an engine issue: https://github.com/godotengine/godot/issues/33184
