### ISSUE TITLE
2d/split_screen_platformer: Nonexistent function 'move_and_slide' in base 'KinematicBody2D'

### ISSUE THREAD

**Issue by twinpigs** [godotengine/godot-demo-projects#36]
Project don't run because of

Invalid call. Nonexistent function 'move_and_slide' in base 'KinematicBody2D' 

In player.gd:38

**Comment by williamd1k0** [comment]
I think you are using Godot 2.1.x.
The `KinematicBody2D::move_and_slide` method does not exist in Godot 2.1.x.
Try using the 2.1 branch https://github.com/godotengine/godot-demo-projects/tree/2.1

**Comment by twinpigs** [comment]
I think this demo needs to be updated according last stable version. Isn't it?

**Comment by williamd1k0** [comment]
I think the demo is already updated.

player.gd:38 (master): https://github.com/godotengine/godot-demo-projects/blob/master/2d/split_screen_platformer/player.gd#L38

player.gd:38 (2.1): https://github.com/godotengine/godot-demo-projects/blob/2.1/2d/split_screen_platformer/player.gd#L38

**Comment by twinpigs** [comment]
Oops. Wrong branch. I'm sorry.

**Comment by williamd1k0** [comment]
No prob
