### ISSUE TITLE
3D platformer error due to whitespace in script

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-demo-projects#360]
In Godot 3.2, the 3D platformer demo doesn't run because of whitespace in one of the scripts.

**Comment by hbina** [comment]
Oh so this is why it was broken. I thought I did something awful in my fork. Any idea which script is causing it?

**Comment by Calinou** [comment]
@hbina I think this is because one of the scripts mixes tabs and spaces for indentation. As of Godot 3.2, you should use either tabs (recommended) or spaces, not both.

**Comment by bojidar-bg** [comment]
It should be working with https://github.com/godotengine/godot/pull/32808, can someone confirm?

**Comment by Calinou** [comment]
I can't reproduce this on commit https://github.com/godotengine/godot/commit/9600fd5dde1f85b7dd2dd8558d52ff86b18651e7. I'll assume this was fixed by the pull request linked above.
