### ISSUE TITLE
Planetary Physics SHA256 Failure

### ISSUE THREAD

**Issue by RobertBColton** [godotengine/godot-demo-projects#362]
Just checking out some of the demos but this one fails the authenticity check. I'd send a pull if I knew how to check the hash myself.

![Planetary Physics SHA256 Failure](https://user-images.githubusercontent.com/3212801/69395700-f3f4be80-0cad-11ea-8f07-01a471659a34.png)

**Comment by bojidar-bg** [comment]
The asset shown in the screenshot is not an official Godot demo. This issue has already been reported on its own repository: https://github.com/ComancheAk/RigidBody-Planetary-Physics-Correct-Stand-Up/issues/1

**Comment by RobertBColton** [comment]
Ah, thanks!
