### ISSUE TITLE
Skeleton2D - rigging and animating demo

### ISSUE THREAD

**Issue by MatejsBalodis** [godotengine/godot-demo-projects#363]
**[Skeleton2D workflow project](https://github.com/rocknightstudios/skeleton2d-demo)** 
was presented at GodotCon 2019 in Poznan.
Right now there are 10 scenes, which are in different stages of process, for example "Character_Step_1.tscn" is a scene only containing 3 nodes for structure, while "Character_Step_10.tscn" has a fully rigged character with an animation.

There was a suggestion to integrate this project as an official demo, so any suggestions and feedback is welcomed!

For process you can watch the presentation [here](https://youtu.be/I2OW-kx3u_4?t=15555)

**Comment by aaronfranke** [comment]
Does anyone know what happened to [this project](https://www.youtube.com/watch?v=P6nQ3E-Cyfk&t=20s) at 0:20?

Anyway, I don't think we should include the demo you linked. The character is a bit... sexual.

**Comment by NathanLovato** [comment]
I don't find the character "sexual", offensive, or anything: it's a female soldier covered from head to toe. She doesn't have sexualized features like large breasts or little clothing. If you think it needs to be discussed or could be offensive as part of the Godot project, then I'd recommend asking women for their opinion.

> we should perhaps add this demo to the demo projects repo

The demo I made with Andreas Esau's Godot bot is incomplete so it wouldn't work now: back then, I encountered too many bugs that prevented me from animating the character. We'd also need Andreas's permission to use his character, although he'd probably be okay with that.

> any suggestions and feedback is welcomed!

The final animated character makes for a nice example, with its complete rig and animation tree. I would just recommend removing all the steps except for the last one to be consistent with the demos in this repository. Having those 10 steps isn't particularly useful to me, as anyway, this doesn't tell you the essential: how to set up polygons, bone influences, and animations.

**Comment by aaronfranke** [comment]
@NathanLovato I e-mailed him recently and got his permission:

![Untitled](https://user-images.githubusercontent.com/1646875/88488552-e5a52380-cf5b-11ea-8062-ed01abc2fb18.png)

**Comment by NathanLovato** [comment]
Thanks for messaging him. I'm not available to work on this at the moment, anyone who'd like to is welcome to tackle this demo.

**Comment by RustyStriker** [comment]
I made around a month ago a prototype with a skeleton2D(using Aaron's texture as a placeholder), i tried cleaning it up and exporting only what is useful...
Can anyone give it a look(Comments on the code are still missing) and give me some feedback?
Link: https://github.com/RustyStriker/Godot_Skeleton2D/tree/master

**Comment by aaronfranke** [comment]
@RustyStriker Sorry for the long delay, that demo is pretty nice and I would greatly appreciate it if you worked on it further and submitted it here. I can give you feedback on your repo before you do so. The shoulders seem to be too high, they shouldn't overlap the head (see [this reference image](https://raw.githubusercontent.com/GDQuest/godot-new-features-v3.1/master/04-03-mesh-deform-2d-character/gbot-reference.png)). Also, all node name should be PascalCase to match the default node naming style.
