### ISSUE TITLE
Dodge the Creeps - Mobs sprites not animated

### ISSUE THREAD

**Issue by rmlz** [godotengine/godot-demo-projects#367]
Hello Guys. This is the first tutorial I did on GODOT. I'm not sure why the Mobs sprites are not running frame by frame. Instead they stick to frame 0 and follow the route until exit the screen.

I have done the tutorial in GODOT website and also have read it 3 times in a row.

I can assure you that mob.gd and main.gd files are perfect. Also, the player animatedSprite is running smoothly.  

Could you show me any lead on which tab or script I should mess up to try to find a resolution.

Thanks very much.

**Comment by rmlz** [comment]
I forgot to .play() the animation!

See you guys.

**Comment by cbscribe** [comment]
The tutorial instructs you to check the "Playing" property on the AnimatedSprite. No need to write any code.

**Comment by Feniks-Gaming** [comment]
@Calinou could we have this issue closed as it was typo mistake by the user but they didn't close it themselves.
