### ISSUE TITLE
Generator audio demo won't play a sound.

### ISSUE THREAD

**Issue by yuvallanger** [godotengine/godot-demo-projects#368]
Godot version: `v3.1.1-stable-official`
This repository's commit: c34a2b423bcbf5134dbccb0836c0da33696621a2

**Comment by Calinou** [comment]
If I recall correctly, procedural audio generation was only implemented in the 3.2 betas. Try using [3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4).

**Comment by Calinou** [comment]
I'll close this as the question was answered.
