### ISSUE TITLE
Close old pull requests?

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-demo-projects#372]
Can we close some of the old pull requests we have PR sat that are dating as far as 2017 it is clear noone is working on those and they are way out of date. We could clean up a bit and keep PRs that actually have a chance of being completed and pass review.

**Comment by aaronfranke** [comment]
Spent the past week triaging, reviewing, merging, and closing. We're now down to 7 PRs instead of over 40, two of which are mine, only one from 2018, and all are recent enough that I will keep them open for now in case the authors get back to them.

So, I'll close this issue as solved.

**Comment by Feniks-Gaming** [comment]
Thanks you for doing ungrateful administrative job it makes things so much cleaner.
