### ISSUE TITLE
LineEdit on Android doesn't work

### ISSUE THREAD

**Issue by antocors** [godotengine/godot-demo-projects#386]
**Which demo project is affected:**

Multiplayer Bomber

**OS/device including version:**

Mac OSX Mojave 10.14.6 (18G103)

**Issue description:**

By tapping on a LineEdit the virtual keyboard pops up but it doesn't work if you type/delete something

I also tried to create a new scene with a Control node and a LineEdit.

BTW It works building from 3.1.2

**Screenshots of issue:**

**Comment by Calinou** [comment]
Can you reproduce this in any other project? If so, this should be reported on the main Godot repository, not here.

**Comment by cenullum** [comment]
yes it doesn't work. On pc build works properly

**Comment by Calinou** [comment]
This is actually a Godot issue which has been solved in 3.2.1 RC1: https://github.com/godotengine/godot/issues/35753
