### ISSUE TITLE
2d/physics_platformer with wrong file name on steam

### ISSUE THREAD

**Issue by ShadowBelmolve** [godotengine/godot-demo-projects#387]
**Which demo project is affected:**
2d/physics_platformer

**OS/device including version:**
Ubuntu 18.04.3 / Godot 3.2

**Issue description:**
I don't know if this repo is the correct one to steam-specific issues but the file `Tileset.tres` is lowercased on steam. In case-sensitive systems godot think that the file does not exist.

**Screenshots of issue:**
![image](https://user-images.githubusercontent.com/43059/73479901-3225f280-436f-11ea-8c6e-ca64d590e0c3.png)

**Comment by aaronfranke** [comment]
What do you mean on Steam? Do you mean you have Godot downloaded through Steam, and then you used the "Templates" tab? That uses content from the [asset lib](https://godotengine.org/asset-library/asset).

**Comment by ShadowBelmolve** [comment]
I've downloaded Godot from steam and it came with a bunch of projects.

![image](https://user-images.githubusercontent.com/43059/74392887-d9c70a00-4dde-11ea-9ef9-8b061fe9026c.png)

**Comment by Sslaxx** [comment]
Godot on Steam comes with the export templates and demo projects.

**Comment by aaronfranke** [comment]
With the release of Godot 3.2.2, the demos that come bundled on Steam have been updated to 87f6a4e3fd772fed563be8175cd90f9968510497.
