### ISSUE TITLE
[TRACKER] Checklist of demos to be updated and tested with Godot 3.1.2

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-demo-projects#389]
These are the folders for which I have personally finished looking through all the demos that are in them, and have ensured that they all work* in Godot 3.1.2 and conform to the style guide.

- [x] 2d #394 #398 #399 #400 #401 (except Platformer)
- [x] 3d #330 #331 #383 #384 #385 #388
- [x] audio #350 #374
- [x] gui #395 
- [x] loading #381
- [x] misc #397 *not all have been tested
- [x] mono #391 #394
- [ ] networking #394 (I'm fine with not testing these for this repo to start using Godot 3.2)
- [x] plugins #376
- [x] viewport #379 #393
- [x] visual_script #364 #394

Hopefully we can finish updating everything soon, so that we can get started on updating to 3.2!

**Comment by fire** [comment]
What is the roadmap for this? Will you be moving to 3.1.2 and then converting to 3.2? How can I help?

**Comment by aaronfranke** [comment]
@fire For any demo, if you find ways to improve it, please do, and I'll review and merge your PR. Improving includes, but is not limited to, converting SCN files to TSCN, conforming to the style guide, simplifying logic if possible, writing documentation and README files, and being consistent with naming. I've been converting all nodes to PascalCase because Godot uses PascalCase by default for nodes.

If it's unchecked above, I haven't looked through all of them yet so you'll save me time for improving those. If it's checked off above, I already looked through it, but if you wanted to improve it further you're welcome to. Right now everything's in 3.1.2, yeah, and we'll convert everything to 3.2 later.

In particular I don't currently have a way to test the multi-touch/Android demos and I only have one good computer so testing the networking demos would be annoying, so if you work on those I'd very much appreciate it.
