### ISSUE TITLE
2D Platformer Demo: All art assets are 2x the necessary size.

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-demo-projects#409]
**Which demo project is affected:**
[2D Platformer Demo (Kinematicbody)](https://godotengine.org/asset-library/asset/120)
[2D Physics Platformer Demo (Rigidbody)](https://godotengine.org/asset-library/asset/119) 

**OS/device including version:**
Affects any OS/device

**Issue description:**

What is the current behavior?
If I would like to use this demo as a starting point for my own pixelart platformer, I can't, because simply alter or replacing art assets results in all kinds of unexpected behaviour, because every visual pixel in the assets is 4 actual pixels (all art is 2x scaled up)

What is the expected behavior?
Expected behavior would be to be able to simply swap the art asset with some other and start poking around in the code changing values here and there, to create a new enemy or slightly different player behavior ... beginner stuff.

Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.

1. Download the and run the project, see something you would like to experiment with,
2. open one of the art assets in your graphics editing software
3. realize the art is not pixel art
4. try to make it pixelart so you can work with it, by scaling it down
5. run the game
6. realize this breaks everything

or

1. Download the and run the project, see something you would like to experiment with,
2. swap out one of the art assets with an existing one of your own
3. run the game
4. realize this breaks everything

**Screenshots of issue:**
It does make simple replacing with other pixelart or amending it impossible for beginners. even for experienced users it's a lot of work and no fun at all. None of the scales in the game matches anymore.

![platformer_demo_pixelsize](https://user-images.githubusercontent.com/47016402/74378761-d33c9080-4de6-11ea-9dc3-6dab0b68d63d.png)

Fixing that is a lot of work even and you already have to know the engine to do this. Which defeats the purpose of this demo as a learning device for newcomers quite substantially.

![platformer_demo_pixelsize2](https://user-images.githubusercontent.com/47016402/74379063-5b229a80-4de7-11ea-87ac-c261001f2fdc.png)

If anyone would want to add another action for the robot dude, they would have to use a 2x2 pixel brush. That would less of a problem if graphic software could also be set to snap the brushtip to a 2x2 pixel grid. But they don't. They snap to single pixels. If I were to set the grid to every 2 pixels and set my brush to snap to the grid, the 2x2 pixel is set in the center, bet the top left corner like it is in the art assets of this project. So you work without snap but constantly have to check and correct your brush strokes to make the 2x2 pixels line up again.

**Comment by Calinou** [comment]
I suppose this is an oversight, but there can be valid reasons to intentionally render pixel art at an high resolution and display it with filtering for smooth scaling. However, this isn't very commonly done in practice and probably isn't the intent here.

**Comment by aaronfranke** [comment]
I believe the intent was to allow the pixel art style without scaling up the sprites. However, the sprites still look pixel perfect when scaled, so it would probably make sense to change this (after #405).

**Comment by golddotasksquestions** [comment]
I can only think this was a mistake, as it makes further development on the sprites incredibly hard. It's definitely not suitable for a demo that is supposed to show off how things are done the right way.

Godot has plenty of in-engine functionality to scale up pixel art. There is absolutely no reason to do this in a simple pixelart platformer like this.
