### ISSUE TITLE
What's "SIDING_CHANGE_SPEED" in 2D/platfomer/player/player.gd?

### ISSUE THREAD

**Issue by TopShimmer** [godotengine/godot-demo-projects#410]
**Which demo project is affected:**
Platformer 2D

**OS/device including version:**
Not OS/device related

**Issue description:**
I was looking at the player movement code and I can't figure out what "SIDING_CHANGE_SPEED" is. I think it's supposed to be how fast the player must be going before they turn to face that direction. Is is supposed to be "SLIDING_CHANGE_SPEED" or am I missing something?

**Comment by aaronfranke** [comment]
This demo has been rewritten, and this constant no longer exists in the rewrite.
