### ISSUE TITLE
3D platformer Godot

### ISSUE THREAD

**Issue by Alex533704** [godotengine/godot-demo-projects#415]
Hello,  i 'm using Godot to make video games ,i use windows 10.
I imported in Godot the 3D Platformer demo  then i launched the demo .
I tried to make the  robot to move by pressing  following keyboard buttons:  S,Z,Q,D  but the robot don't moved, i tryed other buttons but  it doesn' t worked.
The only things that i can do is to jump and shoot 

Can someone help me?

**Comment by Calinou** [comment]
I think you need to use the arrow keys to move in the 3D platformer demo.

**Comment by aaronfranke** [comment]
The demo currently in the asset library is outdated, but the current master version has support for both WASD and arrow keys. @bojidar-bg should hopefully be able to do a release soon for the 3.1 branch, which has these fixes.

**Comment by Alex533704** [comment]
Thank you

Am Di., 18. Feb. 2020 um 19:50 Uhr schrieb Aaron Franke <
notifications@github.com>:

**Comment by Alex533704** [comment]
Thank you

Am Fr., 21. Feb. 2020 um 19:01 Uhr schrieb P@Layer <jogta15@gmail.com>:
