### ISSUE TITLE
Demos for 3.0 alpha

### ISSUE THREAD

**Issue by gforceg** [godotengine/godot-demo-projects#42]
I am having problems importing demos on 3.0.alpha.

I tried to run 2d/platformer by renaming `engine.cfg` to `project.godot` (both files seem INI-ish) and then importing the project.

Once I specify the file and click `import` I see my existing list of imported projects but platformer is not listed.

Is it common to run these demo projects in 3.0.alpha? If so, what steps can I take to get it working?

Thanks!

**Comment by vnen** [comment]
Demos will hardly work on master. You can try to open with 2,1 and export for 3.0, but even then it'll likely need some other tweaks, since the project converter is still WIP.

**Comment by gforceg** [comment]
I think I'll just dual install for now so that I can create my games in for the next version of godot but use the demos as a learning reference.
@vnen Thanks for your quick response!

**Comment by akien-mga** [comment]
If you're just getting started with Godot, I would strongly recommend you stick to version 2.1.x and wait for an official release of 3.0 to try the development branch. The *master* branch is not for the faint of heart, you might get frustrated by its bugs while learning.
(Note that when using this git repo, you should checkout the *2.1* branch to have the versions of the demos that match that release. The current *master* branch expects at least the never-released 2.2 version, and the demos would soon be ported over to 3.0).

**Comment by gforceg** [comment]
@akien-mga, thanks for the advice. I noticed that in #37 and #21. I'm just a bit hard headed. Using 2.2 and so far everything works great.

Thanks again for the support!
