### ISSUE TITLE
Vulkan: 3D in 2D viewport not working

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot-demo-projects#422]
**Godot version:**
Vulkan master
**OS/device including version:**
Arch Linux
**Issue description:**
2D in 3D viewports work (display correctly). But it doesn't work the other way around.
This becomes a problem when the whole display of a game is black because the viewport doesn't render anything (e. g. when using anaglyph effect with two cameras).
Maybe it's not implemented yet.
**Steps to reproduce:**
![3D in 2D - bug](https://user-images.githubusercontent.com/34406967/74562561-656da180-4f6b-11ea-9b1e-5cdab122b21c.png)
(the 3D character is not visible)

**Minimal reproduction project:**
- https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_in_2d (godot demo 3d in 2d)
- https://www.dropbox.com/sh/mhjvlg6zot8and3/AAC7JvaNF_bVst2ILFVW6J6ha?dl=0 (anaglyph_tutorial.zip)

**Comment by LinuxUserGD** [comment]
Should I make another PR with less changes (e. g. not deleting Camera2D as it's a part of a feature) or just wait for engine fix (will try later if I can still reproduce it)? Also don't know if the core devs actually are aware of this issue as it's now moved to the demo projects.

**Comment by aaronfranke** [comment]
I suggest waiting, maybe until next year. The core devs are likely working on many issues and are aware that there are many things that don't work yet. Later, if it's still an issue, we can ping them.

**Comment by clayjohn** [comment]
Yes, please wait until master branch is stable (alpha release at least). Many rendering features have not been implemented yet.

**Comment by aaronfranke** [comment]
By the way, just to clarify why I have this marked as both a bug and an enhancement:

* A demo not working properly is a bug, so it gets the bug label, and the bug will need fixing for 4.0.

* However, fixing it in advance would qualify as an enhancement, since we don't need to fix it now.

**Comment by LinuxUserGD** [comment]
Seems like the viewport only renders with `render_target_update_mode` changed to 3 (always update) and disabled `transparent_bg` (as the background renders black instead of transparent otherwise) which might be a bug in godot4.
Y axis has to be flipped back to `scale = Vector2( 1, 1 )` to render correctly.
For the changes see
https://github.com/LinuxUserGD/godot-demo-projects/commit/939eff0b2bedd96de0585a962b39b196d2f5b5c8 (as PRs are currently restricted to stable godot builds).

**Comment by Calinou** [comment]
@LinuxUserGD See https://github.com/godotengine/godot/issues/40651.

**Comment by aaronfranke** [comment]
@LinuxUserGD Thanks for the information. I plan to port the demos when more of the critical engine bugs are fixed, mostly to do with GDScript, and when the master branch is more stable overall.

**Comment by LinuxUserGD** [comment]
Should be fixed by https://github.com/godotengine/godot-demo-projects/commit/3e3a9e7b6ef92eefe45a6035ae3b4fc92236802f
