### ISSUE TITLE
Seamonkey won't run web game!

### ISSUE THREAD

**Issue by HumanSheeple** [godotengine/godot-demo-projects#44]
![deepinscreenshot20170706204007](https://user-images.githubusercontent.com/28750624/27932958-22e2d39c-628f-11e7-966f-59f9870adf1e.png)

This is the message I get, I enabled the scripts I allowed the cookies no joy, the game needs to be fixed. Saying "change your browser" is not a very inclusive thing to do. Especially when the web game doesn't indicate minimum system requirements.

Here's a link to the godot web game I tried to play: http://godot.eska.me/pub/wasm-platformer/

I'm running Seamonkey 2.46

Here's a snapshot of the java console: 
![deepinscreenshot20170706211407](https://user-images.githubusercontent.com/28750624/27933234-1d30775a-6290-11e7-8616-1d5f3ef819fd.png)

**Comment by akien-mga** [comment]
Well, does Seamonkey support WebAssembly?

**Comment by pwab** [comment]
According to MDN: it does **not** (and the error message "*no native wasm support detected*" is quite clear here).
See: https://developer.mozilla.org/en-US/docs/WebAssembly#Browser_compatibility
You could test it anyway here: http://wasm.studio/ide/project/20/file/WebAssemblyCheck.html

**Comment by Calinou** [comment]
I'll close this, as SeaMonkey doesn't support the required features to run Godot HTML5 exports.
