### ISSUE TITLE
Without coding 2D Platformer template is missing

### ISSUE THREAD

**Issue by Megamega53** [godotengine/godot-demo-projects#457]
**Which demo project is affected:**

"Without coding 2D Plateformer" by Ange 

**OS/device including version:**

Windows 8.1/ Godot 3.2

**Issue description:**

I tried to download this template, but even after the installing it, Godot thinks the project is missing. I don't know if it's because a file is missing from the project, but even though I've installed the folder and its files for the project, I can't open it.

**Comment by aaronfranke** [comment]
This is not an official demo project. Please open an issue on that asset's bug tracker, which you can find by its entry on the asset library.
