### ISSUE TITLE
Dodge the Creeps does not respect window size when exported to HTML5

### ISSUE THREAD

**Issue by markawilson** [godotengine/godot-demo-projects#464]
Not sure if I should report this here or at the Godot engine project, but figured I'd start here in case there's just a project setting that needs to be fixed.

**Which demo project is affected:**

Dodge the Creeps (regular and Mono)

**OS/device including version:**

Windows 10, Firefox 75.0 and Chrome 81.0.4044.92

**Issue description:**

- Exported to HTML5 using stable templates from https://godotengine.org/download/windows
- Started basic Python3 web server in export directory
- Loaded exported page in Firefox or Chrome
- Expected: a sub-region of the canvas containing the game, preferably centered in the browser canvas, which respects the window size or aspect ratio, as depicted at https://docs.godotengine.org/en/stable/getting_started/step_by_step/exporting.html#html5-web
- Observed: game expands to full canvas, centering HUD elements, but using the Path2D coordinates from the Main scene for mobs, which all spawn at the far left (while the player avatar can wander the whole screen) -- see screenshot for a representative example of mob spawning.

Additional info: This also occurs using GLES 2.0, in a version I built following the directions in the documentation linked above.

**Screenshots of issue:**

<img width="961" alt="html5-issue" src="https://user-images.githubusercontent.com/23439518/79052987-0b562900-7c08-11ea-965a-4cc6ea0deea5.png">

**Comment by Calinou** [comment]
Does it work if you run the project locally and resize the window?

**Comment by markawilson** [comment]
Thanks!  Yes, I'm not expecting the game itself to support multiple resolutions.  If your question wasn't rhetorical, the behavior of a resized local window is:
- Partly consistent with the HTML5 (the background ColorRect and HUD elements scale with the window and the mob-spawning path doesn't) 
- Partly inconsistent with the HTML5 (the player and mobs are limited to the 480x720 project-resolution box at upper left, whereas they can move over the entire window in the HTML5 version)

I'm assuming the inconsistency can be explained as "multiple resolutions not supported" being basically equivalent to "undefined behavior."

**However**: While I'm not expecting the game itself to support multiple resolutions, the screencap in the documentation looks like the HTML5 tooling dealt with higher-resolution browser windows by creating a kind of "virtual game window" as an element with the fixed size of the project's window, contained inside the document canvas:

![](https://docs.godotengine.org/en/stable/_images/export_web_example.png)

I guess my question, then, is whether that apparent behavior is:
- Attainable via some setting that isn't currently mentioned in the tutorial *or* set in the sample project (and if so, what is it?)
- No longer consistent at all with the intended behavior of the exporter/project (in which case, maybe the screenshot should be updated?)
- An artifact of browser behavior (and if so, does anyone know the underlying cause?)

**Comment by Calinou** [comment]
You can get this kind of fixed window by swapping out the full-size HTML template with the [fixed-size HTML template](https://github.com/godotengine/godot/blob/3.2.1-stable/misc/dist/html/fixed-size.html). See [Customizing the Web export HTML page](https://docs.godotengine.org/en/latest/tutorials/platform/customizing_html5_shell.html) for more information.

**Comment by markawilson** [comment]
Ah, awesome, thanks for the guidance.

Would it be useful to add an issue or PR over on the godot-docs project, to clarify the exporting-your-first-project tutorial I linked?  That comes well before the HTML customization tutorial and makes no mention of the need to use a custom template.

**Comment by Calinou** [comment]
@markawilson Sure :slightly_smiling_face:

**Comment by aaronfranke** [comment]
In any case, it's not in the scope of this repository to provide custom export settings for the projects. If there is a need for documentation, perhaps open an issue or PR in the [docs repository](https://github.com/godotengine/godot-docs/).
