### ISSUE TITLE
Blur shader not working in 2D Screen-Space Shaders Demo

### ISSUE THREAD

**Issue by nellodotca** [godotengine/godot-demo-projects#467]
**Which demo project is affected:**
https://godotengine.org/asset-library/asset/122

**OS/device including version:**
5.6.11.arch1-1
nvidia 440.82-12

**Issue description:**
Download and import the demo, run it and select the blur shader. It doesn't work but all the others do. I tried copying the shader code to another project but that didn't work either. I tried these versions:

- Godot_v3.2.1-stable_x11.64
- Godot_v3.2-stable_x11.64
- Godot_v3.1.2-stable_x11.64

**Screenshots of issue:**
![image](https://user-images.githubusercontent.com/65245864/81724247-6b83f900-945a-11ea-944b-7ed6dbc0fda2.png)

**Comment by clayjohn** [comment]
Are you using GLES2 by any chance?

**Comment by nellodotca** [comment]
> Are you using GLES2 by any chance?

I am! In the demo description it says

> Renderer: GLES 2 

I guess blur is the exception?

**Comment by clayjohn** [comment]
Was this demo GLES2 by default, or did you switch it to GLES2?

The reason the blue doesn't work is that GLES2 does not compute screen texture mip maps https://docs.godotengine.org/en/latest/tutorials/misc/gles2_gles3_differences.html#screen-texture-mip-maps

**Comment by nellodotca** [comment]
Yeah it was GLES2 by default. I just redownloaded it through the engine templates and the project defaults to GLES2. It's in the project.godot as well

https://github.com/godotengine/godot-demo-projects/blob/57baf0a1b5d1421604498624cb263c3127b713c4/2d/screen_space_shaders/project.godot#L38

**Comment by aaronfranke** [comment]
That would be my fault then. I recently converted most demos to GLES2, testing for regressions, but evidently I didn't click on "Blur" to see that it doesn't work.

@clayjohn Is there any way to make this effect work in GLES2, or should this project be converted back to GLES3?

**Comment by aaronfranke** [comment]
@nellodotca It's been fixed, but please note that in order to get the fixed version you have to get it from GitHub, since the asset library (same source as engine templates) only occasionally gets updated.

**Comment by nellodotca** [comment]
@aaronfranke I actually needed blur for a GLES2 project so if I figure out a way to make it work I'll let you know

**Comment by clayjohn** [comment]
@aaronfranke yea, converting to GLES3 was the only option. The only workaround is to generate the mipmaps manually, but that is not suitable for the demo. 

Thanks for taking care of this!
