### ISSUE TITLE
Setting of format, mix_rate and stereo flag on mic_record

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot-demo-projects#470]
**Which demo project is affected:**
godot-demo-projects/audio/mic_record

**Description:**
The demo and [instructions](https://docs.godotengine.org/en/stable/tutorials/audio/recording_with_microphone.html?highlight=record) show how to print out the format, mix_rate and stereo flags, but not how to set any of them.  

The [AudioStreamSample](https://docs.godotengine.org/en/stable/classes/class_audiostreamsample.html#class-audiostreamsample) class has a format option FORMAT_IMA_ADPCM, which would compress the signal.  Even being able to set the stereo flag to false would save 50% of the bandwidth, as it's generally not relevant when you have a single microphone and therefore should be part of the example.

(If there is no way to set these values, maybe this issue should be filed with the core system.)

**Comment by voylin** [comment]
Whilst working on this, I found that setting stereo to false makes the length of the file longer + make the sound a lot heavier sounding.
I'll be trying to tackle this issue, changing the mix-rate is working properly. 
The things I still want to do are:
- Adding a format option;
- Changing the ui to have a clearer overview of the settings;
- Fix the stereo off issue.

I expect to finish this soon (1-2 days).

**Comment by voylin** [comment]
Sorry for all the commits and closed pull requests, had a difficult time figuring out how to squash and how to make sure the format was correct. ^^"

Everything fixed now and #711 has the features as requested. Made it in the 4.0-dev branch as that's what I am currently running.

**Comment by aaronfranke** [comment]
Fixed by #711 for Godot 4.0. Thanks for the bug report!
