### ISSUE TITLE
Navmesh Project doesn't work after rebaking.

### ISSUE THREAD

**Issue by LynnCelest** [godotengine/godot-demo-projects#472]
For the Nav Mesh Demo on my Windows 10 device. When ever I download the demo and click the Bake NavMesh button in the NavMesh node the demo doesn't work anymore. The Agent stays in place regardless of where ever I click on the screen in game.

Those are all the steps it takes for me to reproduce this bug. I didn't touch anything else in the demo. The demo works if I don't touch the button on the other hand. I discovered this bug because when I was trying to make my own NavMesh the same thing would happen regardless of my children set up. The only thing is that replicating it in this demo is a little weird since one would imagine it baked just fine before the demo was uploaded but doesn't work for me when I re-bake it in my computer.

It gives this bug when ever it runs also "ERROR: _navmesh_unlink: Condition "!nm.linked" is true. At: scene/3d/navigation/cpp:144"

**Comment by Calinou** [comment]
Which Godot version are you using?

**Comment by LynnCelest** [comment]
> Which Godot version are you using?

3.2.1.Stable.Mono though I've tried it on different versions before. I need to double check which ones.

**Comment by LynnCelest** [comment]
So I'm guessing no one is able to replicate it? I'm going to download the github source code and see if  it'll work on my pc with all the latest pulls then. Since this isn't a stable version even if it works it won't really help me with building my game.

**Comment by Calinou** [comment]
> Update: I got stuck for too much of a long time trying to get the compiler to work... (Visual Studio requires a license now??)

You need to connect to a Microsoft account to use Visual Studio Community for more than 30 days after installing it, but using it before that period can be done without an account.

> Configuring for Windows: target=debug, bits=default
Using MinGW
Couldn't parse CXX environment variable to infer compiler version.
Detected GCC version older than 7, which does not fully support C++17. Supported versions are GCC 7, 9 and later. Use a newer GCC version, or Clang 6 or later by passing "use_llvm=yes" to the SCons command line."

You need to grab a recent MinGW-w64 version, not an old MinGW32. [MSYS2](https://www.msys2.org/) provides recent MinGW versions.

**Comment by LynnCelest** [comment]
Hello, I keep trying to build it using all the methods. The only one that actually got half way into building it for me was using Scoop on Power Shell. It still terminated half way and gave me this error though. I feel bad that I can't work efficiently with this stuff...
`[Initial build] yasm -Ithirdparty/libvpx/ -f win64 -D X86_64 -o thirdparty\libvpx\vp8\common\x86\copy_sse2.windows.tools.64.o thirdparty\libvpx\vp8\common\x86\copy_sse2.asm
=====
b''
=====
scons: *** [thirdparty\libvpx\vp8\common\x86\copy_sse2.windows.tools.64.o] Error 3221225781
scons: building terminated because of errors.`

**Comment by aaronfranke** [comment]
@LynnCelest This is not the place to ask for help with compiling the engine. See the documentation: https://docs.godotengine.org/en/latest/development/compiling/index.html and if you are still having issues, try asking the community (anywhere but GitHub) https://godotengine.org/community
