### ISSUE TITLE
gui_in_3d not usable when tree is paused

### ISSUE THREAD

**Issue by makepanic** [godotengine/godot-demo-projects#474]
**Which demo project is affected:**
[gui_in_3d](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/gui_in_3d)

**OS/device including version:**
Linux / 3.2.1.stable.official

**Issue description:**
* If the tree is paused, a `CollisionObject` will not emit `mouse_entered` and `mouse_exited` signals.
* this causes the demo to never set [`is_mouse_inside`](https://github.com/godotengine/godot-demo-projects/blob/master/viewport/gui_in_3d/gui_3d.gd#L31) and in turn breaking the input relaying

**Screenshots of issue:**
https://streamable.com/ini8fw

I found this when implementing a pause screen for a godot VR project. 
I'm unsure if this is an expected limitation of the implementation or if there's a better alternative that could be used to make GUI work in VR (3d).

I've created [#39094](https://github.com/godotengine/godot/issues/39094) in the godotengine repo which duplicated [#38370](https://github.com/godotengine/godot/issues/38370).

If this is a bug in the engine, this issue can probably be closed.

**Comment by aaronfranke** [comment]
Unfortunately, the pause system in Godot is fairly limited. I recently opened a proposal to redesign the pause system, which will allow you to pause only parts of the scene tree, so you can pause specific trees of nodes in your game without pausing the GUI system.

Also, if you are working on a pause screen for VR, check out [GUI in VR](https://godotengine.org/asset-library/asset/604).

**Comment by voylin** [comment]
@aaronfranke Those bug report were solved and closed. I'm looking at which issues I can handle but I guess there already is a demo project for this if I'm correct.
https://github.com/godotengine/godot-demo-projects/tree/master/misc/pause

**Comment by aaronfranke** [comment]
Fixed by #714. Thanks for the bug report!
