### ISSUE TITLE
Possible additions to the 3D Platformer Demo

### ISSUE THREAD

**Issue by HummusSamurai** [godotengine/godot-demo-projects#50]
The following are some changes I made to my local version of the platformer demo (on godot 2) and I was wondering if you'd be interested in a pull request when I port them to godot 3.

Feel free to pick or reject any of my suggestions:

Camera Changes:
- Ability to switch into first person mode, controlled by either mouse or right thumb stick.
- Ability to zoom and rotate the camera in the default 3rd person mode, using mouse or joystick.

Movement Changes:
- Double jump.
- Hold jump to fall slowly i.e. "floating" 
- Also means you can hold jump while jumping to reach full jump potential, similar to games "N" or "super meat boy" (as the prior point changes the player gravity).

Other:
- Press ESC to quit.

p.s. FYI, The demo looks insanely amazing in 1st person mode.

p.p.s. In my local version I was going for a witch theme (I even added a broomstick under the character), so I made the double jumps infinite but very small, so it's basically like a tiny boost to keep the witch gliding in the air. It's a beautiful movement mechanic so I'd love to share the project with anyone interested.

**Comment by Xananax** [comment]
Those are all good changes, but you have to be careful to not make the examples being more than simple examples. The current examples are kept focused and minimal, yet they're still overwhelming for newbies.

Depending on the complexity of your changes, It might be useful to implement them in a different, "advanced examples" repository.

**Comment by HummusSamurai** [comment]
The changes have gone through several iterations, and they are actually extremely minimal and tiny.


The camera changes actually use the same code for rotation/zooming but add parameters for input.
The jumping is also a few simple input parameters and booleans, and I was even to cut away a biiiig chunk of code in an if/else switch.


I actually believe this will even help explain the camera code more, since the automatic camera code didn't make sense to me at first, but with input hooks involved it's much clearer which chunk does what, if only because of calls to check if "rotate" action is active or not, for example.


I will update this post with the project source later today for people to play-test it. It's mind-blowing how much the game feel is improved, and I do believe this makes much more sense as an official demo instead of the old stiff and constrained movement controls.


________________________________

**Comment by HummusSamurai** [comment]
With https://github.com/godotengine/godot/pull/10190 being merged, the camera code would be further simplified and would be very trivial for new users to understand.

**Comment by nagasawamaki** [comment]
Hello, I am amazed what you have added on the 3D platformer demo.
May I ask you to have the source of your new version of the platformer demo?
I am using Godot 2.1.4 so Godot 2 version is fine.
Thank you so much!

**Comment by HummusSamurai** [comment]
Here's the old project if you're really interested.
It's playable, but I didn't fix the bugs because I ported it to Godot 3 (the bugs were fixed and a lot was re-written such as the first-person camera).
I also added a lot more features such as 6-way dashing and a bouncy cat mode.

[broom-life-master-cfc322db723144d52ece4ec1290f4f64c924e793.zip](https://github.com/godotengine/godot-demo-projects/files/1530826/broom-life-master-cfc322db723144d52ece4ec1290f4f64c924e793.zip)

**Comment by nagasawamaki** [comment]
Thank you so much!
I am looking forward to your Godot 3 version

**Comment by HummusSamurai** [comment]
Here's the current project for the Godot 3 version.
[flying-fps-3.zip](https://github.com/godotengine/godot-demo-projects/files/1547527/flying-fps-3.zip)

I haven't decided if I'll open source it yet, so for now I'm just posting the current project.

**Comment by HummusSamurai** [comment]
The controls (if you're on PC):

**WASD** for movement.
**Mouse** to look around.
**LMB** for water blast (like shotgun).
**RMB** for potion throw (like grenade).

**Space** to Jump (hold to "glide").
**Ctrl** to switch to cat mode (bounce on floor, 2x speed but smaller jumps -> better for long-distance flying).
**Shift** to dash/boost. Holding WASD + Shift makes you boost horizontally, Shift + Space boost up, only shift makes you boost down.

**Comment by aaronfranke** [comment]
Thank you for these suggestions. Some of these suggestions seem questionable, primarily because they add complexity to what is supposed to be a simple demo. Also, we have the TPS demo, which is a much nicer 3D third-person platformer demo.

Therefore, I don't think it's worth overhauling this demo, so I'll close this issue.
