### ISSUE TITLE
Add demos that recreate the UI of popular games

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-demo-projects#501]
**Which demo project is affected:**

**Description:**

Make a UI series which takes a look at couple of different popular games and recreates their UI. Godot control nodes are least documented and least cover with tutorials and having multiple demos would help here a lot. 

Would be good to look at couple of different genres something that is common to platformers, something that is common for survival games with ability to change a hot bar, maybe something that we could find in tycoon games with menus and pop ups etc.

**Comment by Calinou** [comment]
> different polar games

I think you meant "different popular games"?

**Comment by Feniks-Gaming** [comment]
Yes I did thanks:)

**Comment by aaronfranke** [comment]
Any particular examples? I recently re-created the old Minecraft UI with the Voxel demo.

**Comment by Feniks-Gaming** [comment]
To be honest at this point any demo of any UI would be helpful. I can't wrap my head around of the control nodes, their descriptions are unclear, behaviour are a mystery. I would take any demo be it minecraft, mario or someone showing how to recreate godot editor layout. I simply can't wrap my head around any of this.

**Comment by aaronfranke** [comment]
Then go look at the existing demos and look at their UI.

**Comment by aaronfranke** [comment]
Closing because there is not really anything actionable in here.
