### ISSUE TITLE
Help with loading/importing the demos

### ISSUE THREAD

**Issue by zayuim** [godotengine/godot-demo-projects#52]
Hey I was just wondering how you would go about loading these demos. I use Linux and I cloned the repo, I believe there is a build command I need to use, But I don't know what it is.

I do apologize as I'm not a developer, But just someone who is interested in seeing the engines capabilities. I would however be interested in updating the readme with some more information about building etc.

Thanks!

**Comment by vnen** [comment]
You don't need any build command. Just open Godot, it'll show the Project Manager. Click on the Scan button and navigate to the directory with the demos, click on Open and its done. The demos will show up in the Project Manager.

**Comment by zayuim** [comment]
@vnen
`SCAN PROJECTS AT: /home/x/godot-demo-projects
found: 0 projects.
`

Are you sure? Keep in mind I cloned the repo, I didn't download from the releases page. I suppose I might have to end up downloading from that though.

**Comment by pwab** [comment]
Correct me if I am wrong, but then you downloaded the master-branch of the godot-demo-projects (which are compatible with godot 3.x) and you try to open them with godot 2.x.

You should use the 2.1 branch instead: https://github.com/godotengine/godot-demo-projects/tree/2.1
Or you should download the projects from the website (because these are the ones from the 2.1 branch).

**Comment by zayuim** [comment]
@pwab Thanks! That worked!

**Comment by pwab** [comment]
You're welcome.  :wink:

**By the way:**
Would it be an option to change the README files of each branch to indicate the compatibility status?
Like so:

_In 2.1 branch:_
> This branch is compatible with Godot 2.1.x

_In master branch:_
> This branch is compatible with latest Godot version

**Comment by zayuim** [comment]
That would be nice, I also think that maybe just to mention the stable
release for download in the readme.
