### ISSUE TITLE
Please make network demos such as the Bomber more secure to cheating

### ISSUE THREAD

**Issue by howlingcatclops** [godotengine/godot-demo-projects#523]
If you want to make demos, at least make them more production worthy, the current bomber implementation is easy to cheat on the client side and does not teach anything to new developers. Also by using the RPC so aggressively each frame, you end up hogging a lot of bandwidth for a simple game.

Sorry for the small rant, but networking is already hard and these types of examples doesn't help the community, only show cases your API, maybe thats your intention, but you should at least point that in your code comments or something.

**Comment by Calinou** [comment]
The issue with a server-authoritative demo is that it pretty much needs client side prediction to have a good feeling to it. Unfortunately, this increases implementation complexity a lot.

> Also by using the RPC so aggressively each frame, you end up hogging a lot of bandwidth for a simple game.

Sending positions 60 times a second isn't that uncommon in 2020. Competitive games such as CS:GO default to a 64 Hz tickrate, and can even be configured to use a 128 Hz tick rate.

**Comment by QbieShay** [comment]
If [this](https://github.com/godotengine/godot/pull/372000) is merged, we could make a different tutorial.
