### ISSUE TITLE
Official platformer 2D demo: background jittering.

### ISSUE THREAD

**Issue by phantomdesvin** [godotengine/godot-demo-projects#527]
**Which demo project is affected:**
https://godotengine.org/asset-library/asset/120 

**OS/device including version:**
Windows 10, AMD RX 580

**Issue description:**
When you move the player, some parts of the tiles of the floor and the walls clearly jitter, and it is not the jitter that is solved with physic step interpolation, it behaves like another kind of jitter, more like if the tiles were actually moving a little bit.

**Comment by Calinou** [comment]
This sounds like something that will be fixed by https://github.com/godotengine/godot/pull/41535.

**Comment by Calinou** [comment]
Fixed in 3.2.4rc1 and later by https://github.com/godotengine/godot/pull/43554.
