### ISSUE TITLE
Godot IAP checkbox not appear in android export settings

### ISSUE THREAD

**Issue by dece441** [godotengine/godot-demo-projects#545]
**Demo project is affected:**

android_iap (In App Purchases) in Mobile folder

**OS/device including version:**

godot version is godot 3.2.1 stable

**Issue description:**

Here it goes wierd, as the project says `make sure to enable "custom build" and GodotPaymentPlugin in your android export setting`. I tried to find the godot payment check boxes but there is no any GodotPaymentplugin Checkboxes in android export settings. Is there any steps that I have to do?? I couldn't find any text or video about this so I asked. Thankyou if you want to help.

**Screenshots of issue:**
![askgit](https://user-images.githubusercontent.com/73749023/97782472-492a9700-1bc4-11eb-8324-bce9a5567817.PNG)
![askgit2](https://user-images.githubusercontent.com/73749023/97782481-4d56b480-1bc4-11eb-8a69-48558fd851b0.PNG)

**Comment by mani144** [comment]
@dece441 its not a bug, did you install Godot In app plugin purchases exactly as the docs ?
you have to download IAP files follow this :

Getting started

If not already done, make sure you have enabled and successfully set up Android Custom Builds. Grab the``GodotGooglePlayBilling`` plugin binary and config from the releases page and put both into res://android/plugins. The plugin should now show up in the Android export settings, where you can enable it.

**Comment by xeil1** [comment]
Hi..

**Comment by xeil1** [comment]
Ho arevuo
