### ISSUE TITLE
Remaking Tween Demo

### ISSUE THREAD

**Issue by Mr-K-GameDev** [godotengine/godot-demo-projects#550]
Now after looking through almost all of the Demos, queit a few Demos stick to my mind, Mainly the
JRPG Demo, Because of it's beautiful UI, OS tests Demo and ofcourse the Tween Demo,
These two *with full honesty* Have the worst looking UI look/Design, So This Issue is suggesting to Remake the
Tween Demo *For now*, and the OS tests Demo

## Things I'll change
1. Change the Overwhelming Amount of Buttons that's Displayed at Once (By using the OptionsButton node)
2. Make a Theme for it, to fit with the Other Demos (2D platformer, JRPG ect...)
3. and Ofcourse..... Rewrite the Whole GDScript file,
Now hear me out, you'll probible say "Why you want to do this if it's functional?"
and to answer that, go ahead and Read the [Tween Demo Script](https://github.com/godotengine/godot-demo-projects/blob/master/2d/tween/main.gd)

.... yup.... it's Very Confussing for anyone else, That didn't Spend a good Half an Hour-ish undertsanding it.
Hopfully you guys will understand, That by doing this, It'll make the Qulity Consistant Over All/Most of the Demos.

Note: I'll be Working on this for the next few days if it got Approved.

**Comment by aaronfranke** [comment]
[Tweens are getting a rewrite in 4.0](https://github.com/godotengine/godot/pull/41794). I agree that the demo can be improved, but note that some of the effort put into the demo might become irrelevant in a year, so only do this if you're OK with that.

A theme seems like a nice idea. Changing the UI might be good idea as it could use improvements, but I think maybe radio buttons (`CheckBox`es with a shared `ButtonGroup`) might be better than `OptionButton`. With the script, it seems fine but there are indeed ways it can be improved, like it's not ideal to fetch nodes every frame using `$` (they should be changed to `onready var`s).

**Comment by Mr-K-GameDev** [comment]
well i guess it wouldn't change that much in Godot 4.0, but still you're right, and also for what ever reason.... i really like Big sized Fonts, Because it's much Clear to see, so i'll try both actually (The check boxs and the OptionsButton).

**Comment by Mr-K-GameDev** [comment]
Remade the Tween Demo, Thanks for the Feedback @aaronfranke 
the remade version is in #548 Pull Request.
