### ISSUE TITLE
3D in 2D demo needlessly complicated (or outdated?)

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-demo-projects#556]
**Which demo project is affected:**
3D in 2D

**Description:**
I clearly remember the first time I looked at the 3D in 2D demo. I thought it's super cool that Godot allows me to do this and that there is a demo available, but there seemed to be a lot of code involved I did not understand the purpose of.

Now that I have used Godot for more than two years instead of two days, I know this demo could showcase 3D in 2D without any code at all.

**All the user needs is a ViewportContainer (make sure to enable "stretch" property) with a Viewport node as child. Then add the 3D scene as child to the Viewport.**

The idea of a "Viewport Sprite" seems like a very custom solution to me (or maybe an old outdated way to do things?)
This code here I thing is way too specific and from my experience serves no real purpose if instead ViewportContainer+Viewport nodes are used:
```
func _ready():
	# We want Godot to load everything but be hidden for a bit.
	viewport_sprite.modulate = Color(1, 1, 1, 0.01)
	#warning-ignore:return_value_discarded
	get_viewport().connect("size_changed", self, "_root_viewport_size_changed")
	viewport_initial_size = viewport.size

	# Assign the sprite's texture to the viewport texture.
	viewport.set_clear_mode(Viewport.CLEAR_MODE_ONLY_NEXT_FRAME)

	# Let two frames pass to make sure the screen was captured.
	yield(get_tree(), "idle_frame")
	yield(get_tree(), "idle_frame")
	viewport_sprite.texture = viewport.get_texture()
	# Hide a little bit longer just in case.
	for _unused in range(50):
		yield(get_tree(), "idle_frame")
	viewport_sprite.modulate = Color.white # Default modulate color.
```

As a beginner, all it did was to confuse me, instead of showing off how simple it is to get the effect I want.
Having a 2D sprite in the same scene on the other hand is great, as it shows that 3D and 2D can coexist in the same scene without any problem. But that 2D Sprite too does not need code either. An AnimatedSprite node or Sprite+AnimationPlayer with Autoplay and loop activated is more than enough for a convincing effect. Same applies to the 3D scene.

**Comment by Calinou** [comment]
For the record, the "wait 50 frames" bit was initially added in https://github.com/godotengine/godot-demo-projects/commit/e3fd4c662c251c7733cb583bf2396ae0c283ea85.
