### ISSUE TITLE
Some demos are not in the most appropriate section

### ISSUE THREAD

**Issue by sarrowsmith** [godotengine/godot-demo-projects#564]
**Which demo project is affected:**
Multiple (see below)

**Description:**
Some demos have a primary feature which is not related to the section they are in. Specifically (arranged by where they currently are):

- "Hierarchical Finite State Machine", "Scene Instancing Demo" and "Saving and Loading (Serialization)" showcase general techniques ("misc") and are only co-incidentally 2D.
- "RegEx (Regular Expressions)" is, again, a general technique which happens to be being demonstrated with a GUI. I'm inclined to say "Translation Demo" is too.
- "GUI in 3D" could equally well be in "3D" or "gui", because that's the *effect* it's demonstrating, even if the techniques is to use viewports. (I'm not so sure about this one, particularly given that ambiguity.)

**Comment by aaronfranke** [comment]
"Saving and Loading (Serialization)" should really be in the "loading" category. I opened #565 for this.

"Hierarchical Finite State Machine", "Scene Instancing Demo" and "RegEx (Regular Expressions)" are a gray area, but I think the way they are now is best. Scene Instancing used to be in the misc category, but I moved it to 2D as an effort to try and reduce the size of "misc". Even though it's not a '2D feature' it's still 2D.

"GUI in 3D" absolutely 100% belongs in the "viewport" category. The entire purpose of the category is to have the various ways to use Viewports. You can argue that it also fits in "3d" or "gui"... but "viewport" is a vastly better category for it.

**Comment by Calinou** [comment]
Closing, as this seems to have been addressed in the best way possible we can do.
