### ISSUE TITLE
Audio Mic Record Demo is not working

### ISSUE THREAD

**Issue by ofrias** [godotengine/godot-demo-projects#572]
**Which demo project is affected:**
Audio Mic Record Demo

**OS/device including version:**
Windows 10, Ubuntu Linux 20.04 and MacOS
Godot v3.2.3

**Issue description:**
No audio, or just noise, is recorded when using this demo.  I have tried on Windows, Linux and MacOS and in all cases the output WAV file contains just silence or noise, depending on the bus layout settings.

**Comment by Calinou** [comment]
Closing in favor of godotengine/godot#33184, since this is an engine bug, not a demo bug.

**Comment by ofrias** [comment]
But I am experiencing the problem also on Windows and MacOS.

**Comment by Calinou** [comment]
> But I am experiencing the problem also on Windows and MacOS.

Then it means the bug also occurs on Windows and macOS, although it seems you're the first user to experience this. I edited the bug report accordingly.

**Comment by Foxomat** [comment]
I am also experiencing this issue on windows. You said you edited the bug, but there everyone still says "open another issue for windows", so what now? New issue or update issue  https://github.com/godotengine/godot/issues/33184 ?
