### ISSUE TITLE
Connected MIDI devices not showing up unless MIDI inputs opened first.

### ISSUE THREAD

**Issue by waimus** [godotengine/godot-demo-projects#603]
**Which demo project is affected:**
Operating System Testing (godot-demo-projects/misc/os_test/os_test.gd)

**OS/device including version:**
Pop!_OS 20.10 (Linux 5.11), Godot 3.2.3.stable Steam, M-Audio Keystation 61 MK3.
Available audio drivers: PulseAudio, ALSA, dummy

**Issue description:**
In the `os_test.gd` line 61, `OS.get_connected_midi_inputs()` does not return anything. 

`OS.open_midi_inputs()` needs to be called first so `OS.get_connected_midi_inputs()` will finally return `Virtual RawMIDI` and `Keystation 61 MK3` in my case. And I guess `OS.close_midi_inputs()` should be called after that since it will not be used any more.

**Comment by Calinou** [comment]
Feel free to open a pull request to fix this :slightly_smiling_face:
