### ISSUE TITLE
Wrong waypoint drawing when switching camera

### ISSUE THREAD

**Issue by skaiware** [godotengine/godot-demo-projects#605]
**Which demo project is affected:**
3D waypoint

**OS/device including version:**
Ubuntu 16 

**Issue description:**
Waypoints are not drawn at the right positions if switching camera at runtime.
Expected the waypoint system to detect and use the right current camera.

**Screenshots of issue:**
Just create 2 cameras in a scene and switch between cameras: see that the waypoints are hard coded to only draw according to the camera found at init/ready time.
See :
onready var camera = get_viewport().get_camera()
in waypoint.gd

A possible fix is to check in waypoint _process() that the 'camera' is current and if not, updating the camera var with the viewport camera. But there is perhaps better.

Tks for this cool util btw.

**Comment by Calinou** [comment]
Getting the camera every frame sounds expensive, but I'd try benchmarking it to see if it makes any significant impact.

**Comment by aaronfranke** [comment]
I'm not sure this is necessary. It's not needed to make the demo work. This kind of thing is easy to do in your own project by just adding a few lines to the script.

**Comment by skaiware** [comment]
Tk @aaronfranke
