### ISSUE TITLE
New Demo: Top Down 2D RPG 

### ISSUE THREAD

**Issue by HummusSamurai** [godotengine/godot-demo-projects#61]
e.g. Pokemon, Zelda LTTP, RPG Maker games.

I would be glad to write the demo and would be open to what features are essential to add (and which shouldn't be).

So far I'm thinking:

Essentials:
* Item and tool usage
* Dialog with NPCs
* Area Transitions (from world to house, world to cave)
* Inventory menu 
* Clear sense of achievement (e.g. quests, journal)

Not Essentials?

Combat: Because it is not possible to decide between real-time and turn-based, and I think it's outside the scope of the demo. I'd be willing to make an "Advanced" version of the demo though, and perhaps a different version for each combat system too.

**Comment by gamergamesz** [comment]
I'll love to see this demo

**Comment by ElfEars** [comment]
All of these components are essentials for almost any godot game, I've always thought an RPG would be a good place to show us how the godot team would implement such systems.
(Personally, it's a pipe dream but I would love to see how they would implement a turn based battle system with stats, stuff like determining whose turn it is, unique enemy ai and initiating the correct code + animations for each attack is HARD!)

**Comment by HeadClot** [comment]
It would be useful to have a 3D Variant of this demo. Just saying :)

**Comment by MuffinMan50** [comment]
Not a big priority at all. Godot is only worried about 3d in the future, and running demos at 20fps is ideal.

**Comment by MoraleMaduzo** [comment]
Not a big priority at all. Godot is only worried about 3d in the future, and running demos at 20fps is ideal.

**Comment by HummusSamurai** [comment]
GDquest will be doing an opensource zelda-like 2D RPG, so let's see where that goes.

I'd be willing to help with that and/or try to make it modular so it can be added to the asset store (so you can "download and install" from the asset store something that would give you some of these features).

**Comment by masphel** [comment]
How about pathfinding, move on click and modular movement sync with both controls from keyboard and contron on mouse click or click on touchscreen. Anyway, any additioanal tutorial is awesome, if you can, do it many people will be gratefull.

**Comment by NathanLovato** [comment]
We've done it for you guys at GDquest, and we have a growing FOSS RPG gameplay engine here: https://github.com/GDquest/godot-turn-based-rpg/
RPGs are pretty complex and I think anything interesting would be a little too big for this repository. Hopefully this addresses the old Godot Patreon request for an RPG demo and this issue.
Our project has keyboard and touch support, pathfinding, NPC interactions, a combat system, levelling, conversations... there's a lot in there already and more to come 😄

Please tell me if it fits for this issue, if so we can finally close it.

**Comment by NathanLovato** [comment]
My bad, I pressed the wrong button!

**Comment by akien-mga** [comment]
Because https://github.com/GDquest/make-pro-2d-games-with-godot and https://github.com/GDquest/godot-turn-based-rpg, this is definitely fixed yes.
