### ISSUE TITLE
Get clipboard doesn't work

### ISSUE THREAD

**Issue by individlab** [godotengine/godot-demo-projects#617]
"Get clipboard contents" doesn't work on iOS (

**Which demo project is affected:**

**OS/device including version:**

**Issue description:**

**Screenshots of issue:**

**Comment by Calinou** [comment]
@individlab Which Godot version did you test this with? Which iOS version is the device running? Did you test this on a physical iOS device or a simulator?

**Comment by individlab** [comment]
v.3.2.3 stable
iOS 14.4.2
Physical iOS device

**Comment by Calinou** [comment]
@individlab Can you try this on 3.3? The 3.2.x series is no longer supported as per the new [release policy](https://docs.godotengine.org/en/latest/about/release_policy.html).

**Comment by individlab** [comment]
@Calinou I've tried with 3.3, didn't help (

**Comment by moth-boi** [comment]
Is this still an issue?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
