### ISSUE TITLE
GUI Input Mapping Demo does not persist keys to disk

### ISSUE THREAD

**Issue by SchwingSK** [godotengine/godot-demo-projects#629]
**Which demo project is affected:**
GUI Input Mapping Demo

**OS/device including version:**
tested with Godot 3.3.2 on Windows 10, does not seem to be Windows-related

**Issue description:**
The project description states:

    - Persists the keys to disk, so they are preserved after the project is restarted.

But it does not seem to do so, as closing the program and running it again resets the input mapping.
Looking at the source code, there's only one script (ActionRemapButton.gd) and I don't see where the persitence would be trigerred. 
I would really love to have an example of input mapping persistence, if there's a Godot API for it. Or does each project have to roll it's own input mapping perssitence ?
Thanks!

**Comment by Calinou** [comment]
Check [Escape's Space input mapping GUI](https://github.com/Calinou/escape-space/blob/master/menu/options_controls.gd) which handles saving the keys to a configuration file. Note that it uses its own Settings singleton, but you can replace it with a generic ConfigFile.
