### ISSUE TITLE
404'd for Godot multitouch demo project

### ISSUE THREAD

**Issue by markthompson** [godotengine/godot-demo-projects#630]
**Which demo project is affected:**
https://github.com/godotengine/godot-demo-projects/tree/3.3-2d4d233/misc/multitouch_view

**Description:**
Just downloaded v3.3.2 and the multitouch_view demo is 404'd.

**Comment by aaronfranke** [comment]
Thanks for the report, it should be fixed now! Let me know if you find any others like this.

**Comment by markthompson** [comment]
@aaronfranke i think i found a few more. what is the preferred way to submit an issue, an issue for each or an issue for all i that find? i can update myself, but i imagine these url's live in a database i don't have access to :)
thanks!

**Comment by aaronfranke** [comment]
@markthompson Yes, the URLs on the Godot Asset Library for these assets are stored in the Godot Asset Library's database. Feel free to just leave a comment on this issue with the details, I will see it.
