### ISSUE TITLE
I cannot download them in Godot Engine.

### ISSUE THREAD

**Issue by lalala-233** [godotengine/godot-demo-projects#646]
I am a Chinese with poor English.
So I use a translator to ask questions.
The link in Godot Engine is wrong.
![image](https://user-images.githubusercontent.com/79189174/131250115-0e3485de-eb12-4e34-b366-eea3e911ee46.png)

**Comment by Calinou** [comment]
Which Godot version are you using? Please fill in the issue template when creating issues on GitHub.

Also, are you behind an HTTP proxy? If so, the asset library within the editor won't work. As a workaround, you can download projects from the asset library's web frontend: https://godotengine.org/asset-library/asset?category=&support%5Bofficial%5D=1&godot_version=&sort=updated&filter=
