### ISSUE TITLE
GUI in 3d acts weirdly in touch screens

### ISSUE THREAD

**Issue by Iakobs** [godotengine/godot-demo-projects#651]
**Which demo project is affected:**
[GUI in 3D](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/gui_in_3d)

**OS/device including version:**
Android 11 / Redmi Note 9 Pro MIUI Global 12.5.1 Stable

**Issue description:**
The first click is always missed when running demo project in touch screens. For example, if you want to click on the button, the first time you click nothing happens, then when you click anywhere in the screen, the button is clicked. It's like the clicking position is registered the first time you click, and then used the next time you click, liker there is a delay in the clicking action. Same happens with the draggin action.

*Steps to reproduce:*

- Run the demo project in a touch screen device
- Try to click on any control node, nothing happens.
- Click anywhere in the screen, the control you were trying to click is now clicked.

**Comment by Calinou** [comment]
It sounds like the **When Changed** viewport update mode is causing issues. Try changing the 2D viewport's update mode to **Always** in the inspector, then export the project to Android again.

**Comment by Iakobs** [comment]
Hi! Thanks a lot for the quick answer! 

The update mode is already set to Always in the viewport displaying the 2d GUI, so it didn't help to solve the issue.

I'm interested in your suggestion, though, how would you recommend implementing a 2d GUI in a 3d game? I thought this was the only way to keep the UI in place regardless of the aspect ratio of the screen, since the stretching options don't work for 3d games. I'm sorry if this is not the place for this discussion. My use case is simply having some buttons around the screen, in a fixed place, like this

![imagen](https://user-images.githubusercontent.com/10604600/135125891-e901bf69-075f-4ee7-9e8e-4c773f430916.png)


Either way, if you think it doesn't worth the effort solving this problem I don't want to waste anybody's time on it :)

**Comment by Calinou** [comment]
> I'm interested in your suggestion, though, how would you recommend implementing a 2d GUI in a 3d game? I thought this was the only way to keep the UI in place regardless of the aspect ratio of the screen, since the stretching options don't work for 3d games. I'm sorry if this is not the place for this discussion. My use case is simply having some buttons around the screen, in a fixed place, like this

Godot has built-in support for [multiple resolutions and aspect ratios](https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html). Use the `2d` stretch mode and `expand` stretch aspect then configure your UI nodes' anchors accordingly.

**Comment by Iakobs** [comment]
Thanks a lot for your guidance!

regarding the issue I raised, should I close it?

**Comment by Calinou** [comment]
> Thanks a lot for your guidance!
> 
> regarding the issue I raised, should I close it?

Indeed, I think it's better to close it here. You could create an issue on the main Godot repository, as this is likely an engine issue.
