### ISSUE TITLE
mic_record freezes when playing recorded audio

### ISSUE THREAD

**Issue by benjarmstrong** [godotengine/godot-demo-projects#661]
**Which demo project is affected:**
/audio/mic_record/

**OS/device including version:**
Tested on Godot 3.4 / Windows 10, likely affects all platforms

**Issue description:**
Demo freezes when attempting to play back recorded audio

**Screenshots of issue:**
N/A

The problem is in the script attached to the main scene root node:

    func _on_PlayButton_pressed():
        print("Play button pressed")
        print(recording)
        print(recording.format)
        print(recording.mix_rate)
        print(recording.stereo)
        var data = recording.get_data()
        print(data)
        print(data.size())
        $AudioStreamPlayer.stream = recording
        $AudioStreamPlayer.play()

print(data) prints a byte array of the entire recording to the console. It doesn't actually crash Godot, but it does make it unresponsive for an extremely long time, even for short recordings. Removing this line fixes the issue.

IMO we should simply remove this line as it doesn't really provide any benefit to the demo.

**Comment by akien-mga** [comment]
The change in 3.4 probably comes from https://github.com/godotengine/godot/pull/53655, previously a `PoolByteArray` would only be printed as `[PoolByteArray]`, while now it's actually printing the whole contents of the array.

We might want to add a way to set an ellipsis for Very Long Arrays™ in general when printing (CC @pycbouh) to prevent users from shooting themselves in the foot like this, but yeah, for the demo this line should simply be removed.

**Comment by benjarmstrong** [comment]
Ah that'd be it. This was originally reported as an engine issue with 3.4 that was not present in 3.3.
