### ISSUE TITLE
3D Physics test : change color when rigidbody sleeps

### ISSUE THREAD

**Issue by alan-man** [godotengine/godot-demo-projects#668]
**Which demo project is affected:**
3d/physics_tests

**Description:**
When working with physics, it is key to check if rigidbodies are in sleep mode or not. 
@pouleyKetchoupp Would you accept a PR that changes the color when the body sleeps ?
Kind

**Comment by pouleyKetchoupp** [comment]
@alan-man Yes, doing a slight change in color when the body sleeps is an enhancement I've had on my list but never got the time to do, it would be welcome.

It's a change in the engine core though, not the physics demo project. Feel free to come discuss on the developers chat if you need some hints about where to look!

**Comment by pouleyKetchoupp** [comment]
I'm closing this issue since it's not directly related to the demo projects.
