### ISSUE TITLE
Add a 3D Rigidbody character demo

### ISSUE THREAD

**Issue by alan-man** [godotengine/godot-demo-projects#669]
**Which demo project is affected:**
None, new demo

**Description:**
As today, there is only a kinematic character demo in 3d/kinematic_character.
Kinematic bodies are not friendly with other rigidbodies. 
Gameplay using physics (eg Fall Guys) needs a rigidbody character. 
Would you accept a PR that add a rigidbody character demo project ?
Kind

**Comment by aaronfranke** [comment]
There is a 2D one currently, so maybe it would make sense to have a 3D one.

**Comment by alan-man** [comment]
@Calinou What do you think : would you accept a PR ?

**Comment by Calinou** [comment]
> @Calinou What do you think : would you accept a PR ?

Sure, feel free to open a pull request for this :slightly_smiling_face: 

I recommend using the Kinematic Character 3D demo as a base, and modifying it to use a RigidBody instead.

**Comment by alan-man** [comment]
Thank you for the help. Will do.

**Comment by aaronfranke** [comment]
Added by #675.
