### ISSUE TITLE
3D Scaling does not stay when scaling window

### ISSUE THREAD

**Issue by voylin** [godotengine/godot-demo-projects#698]
**Which demo project is affected:**

https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/viewport/3d_scaling

**OS/device including version:**

Arch Linux-lts with i3 window manager

**Issue description:**

When resizing the main window, the scaling is undone.
Also something else I noticed is that the window scaling mode in project settings is still 2d, but with the recent changes, that should be changed to one of the new modes, however in the new modes this doesn't seem to work at all.

**Comment by voylin** [comment]
> Can you reproduce this in the 3.4.4 demo?
> 
> > Also something else I noticed is that the window scaling mode in project settings is still 2d, but with the recent changes, that should be changed to one of the new modes, however in the new modes this doesn't seem to work at all.
> 
> The stretch should be changed to `canvas_items`, which is the new name of the `2d` stretch mode.

The 3.4.4 version works perfectly for me.

**Comment by Calinou** [comment]
cc @aaronfranke

**Comment by aaronfranke** [comment]
Fixed by #699
