### ISSUE TITLE
More comments and fewer chained expressions would be much easier to understand

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot-demo-projects#7]
_(Moving from godotengine/godot#1617, originally submitted by @Ace-Dragon, propsal for moving by @djrm)_

Currently, many code snippets are done with lots of chaining, to the point of getting the user lost:

``` gdscript
var a = get_something().do_something().third_thing()
```

Obviously, it would become much more readable/understandable if it is done like:

``` gdscript
var something = get_something()
var something_modified = something.do_something()
var third = something_modified.third_thing()
```

Another problem is the lack of comments, which has the problem of completely discouraging users at some point, especially if they don't have the knowledge of reading through loads of documentation efficiently and understanding what methods do by intuition.

``` gdscript
var something = get_something() # Get blah
var something_modified = something.do_something() # Foo the something
var third = something_modified.third_thing() # Bar the foobar of the foo of the blah
```

As @Wend1go noticed, the [navmesh demo](https://github.com/godotengine/godot-demo-projects/tree/master/3d/navmesh) is a great example of this issue. Consider [navigation.gd:18-44](https://github.com/godotengine/godot-demo-projects/blob/master/3d/navmesh/navmesh.gd#L18-L44) and [:50-66](https://github.com/godotengine/godot-demo-projects/blob/master/3d/navmesh/navmesh.gd#L50-L66), which contain in total a single comment for as much as 30-40 lines of complex vector math and single-character variables.

**Comment by NathanLovato** [comment]
Chris did a lot of code cleanup for 3.0 and fixed this for the most part so closing.
