### ISSUE TITLE
Translation Demo not working, text doesn't translate (4.0-dev)

### ISSUE THREAD

**Issue by voylin** [godotengine/godot-demo-projects#703]
**Which demo project is affected:**
https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/gui/translation

**OS/device including version:**
Arch linux lts-5.15.31-1 With i3 Window manager

**Issue description:**
The demo does not translate sound, does not change flag and does not play any other audio than the English audio.

**Comment by aaronfranke** [comment]
Fixed by #704 for Godot 4.0.
