### ISSUE TITLE
simple_multiplayer - player not moving

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot-demo-projects#73]
Godot  https://github.com/GodotBuilder/godot-builds/releases/tag/master_20171011

Placing many bombs sometimes lead into a stunned state where the player is not animating or moving.

I am not sure if this fixes since it only happens sometimes. I was not able to reproduce it anymore.
(I moved the stunned reset to the end of the animation)

![image](https://user-images.githubusercontent.com/4741886/31513849-e071281c-af8f-11e7-8f1c-06c89eed947f.png)

**Comment by aaronfranke** [comment]
Can't reproduce in the latest version of the demo project with Godot 3.2. If you are still having issues, feel free to continue the discussion below.
