### ISSUE TITLE
Update demo uploads on the asset library for 3.5

### ISSUE THREAD

**Issue by thearduinoguy** [godotengine/godot-demo-projects#780]
**Which demo project is affected:**
Audio Mic Record

**OS/device including version:**
Win 10

**Issue description:**
Audio Mic Record no longer in the asset library

**Screenshots of issue:**

**Comment by aaronfranke** [comment]
https://godotengine.org/asset-library/asset/527

**Comment by Calinou** [comment]
The demos on the asset library should be updated for 3.5.

**Comment by jtnicholl** [comment]
They still show up if you search from the project manager, just not the project editor.

**Comment by Calinou** [comment]
> They still show up if you search from the project manager, just not the project editor.

This is expected, as the project manager only shows templates/projects/demos while the editor doesn't display those categories.

**Comment by jtnicholl** [comment]
> > They still show up if you search from the project manager, just not the project editor.
> 
> This is expected, as the project manager only shows templates/projects/demos while the editor doesn't display those categories. (You can't install a project from within another project.)

You're right, I tried in 3.4.5 and it doesn't show up there either, same as 3.5. So the Godot version of the assets has nothing to do with it, then?

**Comment by Calinou** [comment]
> So the Godot version of the assets has nothing to do with it, then?

For the project manager/editor *category* filtering, no. For the version filtering (which affects both project manager and editor), yes.

**Comment by aaronfranke** [comment]
Done after #827.

Release: https://github.com/godotengine/godot-demo-projects/releases/tag/3.5-9e68af3
