### ISSUE TITLE
name=GPUParticles2D type=CPUParticles2D

### ISSUE THREAD

**Issue by stevecotton** [godotengine/godot-demo-projects#785]
**Which demo project is affected:**
* 2d/physics_platformer
* 2d/platformer
* 3d/platformer

**Issue description:**
Some of the demos in the `4.0-dev` branch have instances of CPUParticles2D that are named GPUParticles2D. The discrepancy is already present in the `master` branch, although it's less obvious without the rename of Particles2D to GPUParticles2D.

Similar applies for 3D, and the first one on this list mixes both "3D" and "2D":
```
2d/physics_platformer/coin/Coin.tscn:[node name="GPUParticles3D" type="CPUParticles2D" parent="."]
2d/physics_platformer/player/Bullet.tscn:[node name="GPUParticles2D" type="CPUParticles2D" parent="."]
2d/platformer/src/Objects/Bullet.tscn:[node name="GPUParticles2D" type="CPUParticles2D" parent="."]
3d/platformer/coin/coin.tscn:[node name="GPUParticles3D" type="CPUParticles3D" parent="."]
3d/platformer/player/bullet/bullet.tscn:[node name="GPUParticles3D" type="CPUParticles3D" parent="."]
```

**Comment by aaronfranke** [comment]
We could likely change all of the node names to just "Particles" with no prefix or suffix. The type is more of an implementation detail, while the name can be more general purpose.
