### ISSUE TITLE
Web demos are broken

### ISSUE THREAD

**Issue by rpaladin** [godotengine/godot-demo-projects#786]
**Bug description:** Game does not start. Tested in both latest Edge and Firefox versions, no luck.
**Reference link:** <https://godotengine.github.io/godot-demo-projects/3d/platformer/>

## Console Errors - Edge

![image](https://user-images.githubusercontent.com/69180012/198813711-f300f8e6-509f-44a3-9555-69bbb6269162.png)

## Console Errors - Firefox

![image](https://user-images.githubusercontent.com/69180012/198813692-d3aa29f5-5ef1-4103-8777-46ef52eaaa89.png)

**Comment by Calinou** [comment]
I can confirm this on Firefox 105 (Linux). The online demos are using a old Godot version (3.3.3) and it needs to be updated to 3.5.

**Comment by antonio-hickey** [comment]
Does Web Signaling Demo work for anyone else actually exported to web? 

I'm on Godot 4.1.1, and exported the Web Signaling Demo to HTML5, and set up my signaling server but the web is not calling it. (it does from being ran in Godot).

**Comment by Calinou** [comment]
> I'm on Godot 4.1.1, and exported the Web Signaling Demo to HTML5, and set up my signaling server but the web is not calling it. (it does from being ran in Godot).

The demo was last updated for 4.0.beta4, so I don't know if it's expected to work. cc @Faless

**Comment by JoelCreatesGames** [comment]
confirming that https://godotengine.github.io/godot-demo-projects/3d/platformer/ and https://godotengine.github.io/godot-demo-projects/2d/isometric/ are still broken

I get `indirect call to null` in firefox and `null function or function signature mismatch` on chrome

**Comment by FracPro** [comment]
Yeah same issue, none of it works out of the box, another home grown adventure appreciate the hard work though!

**Comment by Calinou** [comment]
@FracPro Please open a new issue with more details (which demos don't work, which OS/browser you're using, and so on).

**Comment by MariaCodesXoXo** [comment]
I've tried the demo https://godotengine.github.io/godot-demo-projects/3d/platformer/ on both Microsoft edge and duckduckgo and it worked flawlessly, the issue might've now become only firefox specific as [comment ](https://github.com/godotengine/godot-demo-projects/issues/786#issuecomment-1295969701) suggests

<img width="1917" height="1023" alt="Image" src="https://github.com/user-attachments/assets/120e87e4-0ae6-4660-9edd-193f59ccefcb" />

**Comment by MariaCodesXoXo** [comment]
> confirming that https://godotengine.github.io/godot-demo-projects/3d/platformer/ and https://godotengine.github.io/godot-demo-projects/2d/isometric/ are still broken
> 
> I get `indirect call to null` in firefox and `null function or function signature mismatch` on chrome

Initial run on chrome and duckduckgo returns a black screen, refreshing the page shows the godot loading screen then the game starts just fine 

<img width="1913" height="1028" alt="Image" src="https://github.com/user-attachments/assets/ee026577-64be-4098-b9ea-35faa778e61f" />
