### ISSUE TITLE
WebSocket Multiplayer - Server doesnt receive peer disconnect event

### ISSUE THREAD

**Issue by OsakiTsukiko** [godotengine/godot-demo-projects#793]
**Which demo project is affected:**
WebSocket Multiplayer

**OS/device including version:**
Arch Linux x86_64, Godot v3.5.1.stable.official

**Issue description:**
Server doesnt receive event when client peer disconnects using the disconnect button (although it does when client window is closed without using the disconnect button)
Expected: network_peer_disconnected to be fired
Result: it is not when using the disconnect button, leaving a "zombie" player in server list
It does disconnect when client connects again

**Comment by Faless** [comment]
Thanks for reporting this issue! I've opened #795 which should fix it, would be great if you could also test that the fix is working on your side :).

**Comment by OsakiTsukiko** [comment]
Thanks, works perfectly!

**Comment by OsakiTsukiko** [comment]
fixed in 3a23fdbe6ad394d1632018ccf773f4f03a0ef9e5
