### ISSUE TITLE
Bomber multiplayer demo: Bomb appears in front of player and name

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-demo-projects#796]
**Which demo project is affected:**
https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/networking/multiplayer_bomber

**OS/device including version:**
Win10 Nvidea 765M

**Issue description:**

Bomb appears to be sorted in front of player character and name:

https://user-images.githubusercontent.com/47016402/204101490-9fd6dec1-6e9d-4a23-aeeb-27b546e32706.mp4

The ysort property seems to be disabled, so I have tried to enable ysort, but the ysort system changed in Godot4 and I have not figured out how to make it work properly.

Note: This issue is present in the Godot3 Bomber Multiplayer Demo as well.

**Comment by Calinou** [comment]
While fixing this, it would also be a good opportunity to add outlines to player label names, so that they're readable more easily.

**Comment by moth-boi** [comment]
This can be closed now @Calinou.

**Comment by aaronfranke** [comment]
Fixed by #834.
