### ISSUE TITLE
Bomber multiplayer demo: Bomb explosion not fully visible

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-demo-projects#798]
**Which demo project is affected:**

https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/networking/multiplayer_bomber

**OS/device including version:**

Win 10, Nvidea 765M

**Issue description:**

The bomb explosion should spawn explosion sprites along a few tiles it affects, but it only shows explosion sprite right at the tile where it exploded:

https://user-images.githubusercontent.com/47016402/204102179-1acbd140-402e-47f8-8204-c7d1180ce004.mp4

For comparison here is the Godot3 Bomber Multiplayer demo:

https://user-images.githubusercontent.com/47016402/204102307-0eda28f9-222f-4c79-8379-1b5cefe98a16.mp4

**Comment by moth-boi** [comment]
Unless there is more to this issue, it can be closed now.

**Comment by aaronfranke** [comment]
Fixed by #833.
