### ISSUE TITLE
Downloading and testing specific demos is a pain, because I have to download the whole repo

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-demo-projects#799]
**Which demo project is affected:**
Any of the Godot4 demos in this repo.

**Description:**
I sporadically want to download specific demos to test Godot4 features, but never all demos. Because of how Git and Github works, I can only ever download the whole repo (which has 600MB!), without manually downloading and recreating each file and resource individually. What is worse is how you basically always have to do this whenever you want to test a specific demo as those demos obviously have to be updated regularly to work with the new engine updates.

This is an absolute pain and the sole reason why I try to avoid using any of the demos unless I really have to.

Downloading the latest up-to-date demos should not need a Github account or Git experience. This should be as accessible and easy as possible to make more users (especially the fast majority of less experienced users) try and test Godot4 features.

Using sparse-checkout with Git still downloads the whole repo (600MB!), and is like the polar opposite of user friendliness. Good luck finding a beginner Git user able to [figure this out](https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository).

Ideas for solutions: 

- Don't host those demos exclusively as a repo on Github. Maybe they can be uploaded and hosted on a tux server as well, just like the Godot engine releases? And only use the Github repos to collaboratively work on the demos?
- Individual repos for each demo? Would totally clutter the godotengine Github user profile, so maybe as a different Github user, like godotdemo? (Imho cleanest solution, most desirable)
- I saw someone on StackOverflow mentioning branches as a workaround. (Sound like a total hack to me, therefore least desirable)

**Comment by aaronfranke** [comment]
If you use `git clone` to download the repo, you can later update your downloaded copy using Git operations, instead of having to download everything all over again.

Stable versions are already packaged individually: https://github.com/godotengine/godot-demo-projects/releases

**Comment by YuriSizov** [comment]
> Stable versions are already packaged individually: https://github.com/godotengine/godot-demo-projects/releases

Asset Library too, correct? E.g. for 3.5: https://godotengine.org/asset-library/asset?category=10&support%5Bofficial%5D=1&godot_version=3.5&sort=updated&filter=

Though the 4.0 versions are not available yet because we are not there yet.

**Comment by golddotasksquestions** [comment]
@aaronfranke I don't want 600MB of files on my computer I never use or care for. The individual demo I want to download has make a few KB and is likely deleted after I done my testing.

**Comment by jtnicholl** [comment]
> Downloading the latest up-to-date demos should not need a Github account or Git experience. This should be as accessible and easy as possible to make more users (especially the fast majority of less experienced users) try and test Godot4 features.

> Also you are missing my point on how testing should be accessible to users who are not Git pros.

This is already the case for the Godot 3.x demos. Godot 4 is not stable and the demos aren't all ported yet, IMO they don't need to be accessible to complete newbies who can't even do a Git clone.
Also, someone using Godot 4 betas likely already has experience with Godot 3, and therefore has less need for these demos.

**Comment by aaronfranke** [comment]
We're not changing the design of this repository just to save 600 MB on your computer, sorry.

If the space is a problem for you, I will buy you a 128 GB flash drive for $10.

> Also you are missing my point on how testing should be accessible to users who are not Git pros.

`git clone` and `git pull` are fairly easy operations. All of this can be done with a GUI app too. You don't have to be a Git pro to do these things. However, Git skills are highly useful for contributing to any project on **Git**Hub, so I would recommend you pick up those skills too.

**Comment by golddotasksquestions** [comment]
@jtnicholl

> This is already the case for the Godot 3.x demos. 

I explicitly mentioned in my issue description this as a Godot 4 issue. I don't know why you guys are talking about Godot3. 

**I'm talking about testing Godot4 features here.**

>Godot 4 is not stable and the demos aren't all ported yet, IMO they don't need to be accessible to complete newbies who can't even do a Git clone.

This is some elitist gatekeeping BS. If you want Godot4 to be accessible not just to hardcore veteran users, you need beginner and non veteran users to test it just the same. You need testers with all kinds of backgrounds and skills.


@aaronfranke 

It's not a harddrive issue. I have plenty of available harddrive space available. It's an accessibility and convenience issue.
The current repo structure makes it far less convenient for non hardcore users to participate and test new features. 

Closing and archiving this discussion is really not exactly a sign of trying to open up for less experienced people. Makes me wonder what it is Godot contributors want. On one side you keep asking for more participation and testing and reporting, on other side you immediately close a discussion for improving this process. Congrats on shooting yourself in the foot, I guess.

**Comment by YuriSizov** [comment]
@golddotasksquestions Your concern has been noted and appreciated. We currently don't have plans to change the structure of the repository, but we are aware of this use-case. For casual users we recommend using published releases here or in the Asset Library. Yes, they don't update too often, and we can improve that with some automation, but ultimately it shouldn't be a big issue, and we don't mind if someone reports a bug that's already been addressed in a actual, but not published version of one of the demos.

We do want users and fellow developers to report issues as soon as possible. Sometimes there are hoops to jump through to participate, and that's something for us to work through. Still, the barrier for entry is relatively low for anyone who does at least some sort of development. People who are way less experienced should better wait for a more stable release and officially published demos to participate. It would be easier for everyone at that point, and for now they can trust in other users who are more experienced to do the hard part.

This thread is closed, but not locked or archived. You can still discuss the possible ways forward, but only if we all stick to the Code of Conduct, and calm down a bit. Thanks.

**Comment by Calinou** [comment]
You can use third-party tools such as  https://download-directory.github.io/ to download a single folder from a GitHub repository.

**Comment by golddotasksquestions** [comment]
@Calinou Thank you, this works really well! I'll be using this a lot!
