### ISSUE TITLE
OS test demo

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-demo-projects#8]
Moved from https://github.com/godotengine/godot/issues/3142:

> The OS class provides an abstraction layer over the platform-dependent code.
> The engine now has code for something like 13 platforms.
> It would be nice to have a demo that tests all (or most) of the OS class methods.
> This way it would be much more easier to test and compare different platform implementations.
> And also find bugs in the platform-dependent code.
> It will also be very helpful when adding support for a new platform.

**Comment by Calinou** [comment]
How would it look like? Would it just have a Label or RichTextLabel that displays the result of various OS calls, with some buttons to trigger actions?

**Comment by aaronfranke** [comment]
If such a demo were to exist, we could also make use of the [C# defines](https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_features.html#preprocessor-defines) added in Godot 3.2.

**Comment by Calinou** [comment]
I started working on an OS testing demo in this branch: https://github.com/Calinou/godot-demo-projects/tree/add-os-testing-demo

Feel free to check it out and suggest features that should be added.
