### ISSUE TITLE
input_callback: AudioUnitRender failed, code: -10863

### ISSUE THREAD

**Issue by anwarhussain29** [godotengine/godot-demo-projects#808]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/42167842/209141337-39b9c8aa-2a6d-40be-9017-86e168a0c4fd.png">

**Which demo project is affected:**

**OS/device including version:**
Mac OS Monterey
12.6

**Issue description:**
E 0:00:00.503   input_callback: AudioUnitRender failed, code: -10863
  <C++ Source>  drivers/coreaudio/audio_driver_coreaudio.cpp:237 @ input_callback()

**Screenshots of issue:**
<img width="866" alt="image" src="https://user-images.githubusercontent.com/42167842/209141008-c54b5062-efc5-4a45-a3b2-d121247012a6.png">

**Comment by aaronfranke** [comment]
You did not state which demo this is from, so I can only assume this was meant to be an engine bug report.
