### ISSUE TITLE
Platformer 3D has broken dependency in tiles.scn

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-demo-projects#81]
The `tiles.scn` scene (source for the MeshLibrary) has a dependency on `texture.tex`, which is no longer there in 3.0. It should be `texture.png` directly.

**Comment by t-karcher** [comment]
This was fixed more than a year ago and can be closed, right?

**Comment by Calinou** [comment]
I can confirm the issue is fixed as of https://github.com/godotengine/godot-demo-projects/commit/47be86af932b77f65b00dde25f046ce2e1499bb2.
