### ISSUE TITLE
Regex demo incompatible with current master branch

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-demo-projects#83]
Current master branch for Godot 3.0.

The regex demo is broken. CC @leezh @StraToN

**Comment by StraToN** [comment]
@akien-mga Could this be related to https://github.com/godotengine/godot/pull/10148/commits/e3e2f063244804bb147418dc219ba6db8219304b ?

**Comment by akien-mga** [comment]
For sure.

**Comment by StraToN** [comment]
Ok then, I'll look into it.

**Comment by akien-mga** [comment]
Fixed by #85.
