### ISSUE TITLE
TODO: 3D Inverse Kinematics `Remove all of the old bone nodes`

### ISSUE THREAD

**Issue by EyadTamer999** [godotengine/godot-demo-projects#853]
**Which demo project is affected:**

[3d/ik/addons/sade/ik_fabrik.gd](https://github.com/godotengine/godot-demo-projects/blob/8e2dbf3f557c436fe443384c6bfa403ed1552e48/3d/ik/addons/sade/ik_fabrik.gd)

3D Inverse Kinematics

**Description:**
TODO left unsolved, and could be possible cause to #697 (?)

last commit to file was in Oct 1, 2020

`
 #Remove all of the old bone nodes
 #TODO: (not a huge concern, as these can be removed in the editor)
`

**Comment by Calinou** [comment]
The demo needs to be updated to 4.0 first. However, IK is still in flux (and broken for many use cases),

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-demo-projects/issues/984.

**Comment by GeorgeS2019** [comment]
https://github.com/godotengine/godot-demo-projects/issues/984
