### ISSUE TITLE
2d/role_playing_game broken on godot v4.0

### ISSUE THREAD

**Issue by lilac-eclipse** [godotengine/godot-demo-projects#879]
**Which demo project is affected:**
2d/role_playing_game

**OS/device including version:**
Windows 11

**Issue description:**
Unable to run demo from latest commit on master. Errors on Game.gd include:
```
Line 10:Value of type "Node" cannot be assigned to a variable of type "NodePath"
```
Though many other errors exist throughout the project.

**Screenshots of issue:**

**Comment by InfiniteProductions** [comment]
In fact, the demo has not been yet converted to run with Godot 4 (for instance it use Tweens the old way).
