### ISSUE TITLE
Adding different material roughness parameters for easy testing to 3d/material_tests

### ISSUE THREAD

**Issue by armmah** [godotengine/godot-demo-projects#897]
The material tests scene demo has a range of materials currently on display for the demo, but it lacks a grid of abstract materials with specific increments for testing purposes of PBR.

While iterating on SSR I set up this grid that has both dielectrics and metals, and varying roughness value from 1.0 on the left to 0.0 on the right by a 0.1 step (simply duplicating the materials and setting the metal and roughness parameters on it).

![image](https://user-images.githubusercontent.com/31006916/228181726-55e939d3-0ced-4fcb-9b01-220b77994305.png)

No changes done to the demo itself, the new platform is outside of the camera frustum when going through the materials in the demo.
![image](https://user-images.githubusercontent.com/31006916/228182205-2ef7bdee-b16e-43cd-9785-433a37917540.png)

I already have this setup locally and if this can be useful I can open a PR.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot-demo-projects/pull/809 has a setup with all roughness and metallic levels, but I think it makes sense to add this to the Material Testers demo as well.

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by armmah** [comment]
`visible = false` added on a separate dedicated script, didn't want to introduce unncessary dependencies on the demo test script.

PR created https://github.com/godotengine/godot-demo-projects/pull/899
