### ISSUE TITLE
MicRecord Demo AudioUnitRender failed on MacOS

### ISSUE THREAD

**Issue by turnercore** [godotengine/godot-demo-projects#900]
**Which demo project is affected:**
godot-demo-projects/godot-audio-demo/audio/mic_record

**OS/device including version:**
Apple M1 Pro 16GB
Ventura 13.2.1

**Issue description:**
When loading the demo project get multiple errors a second, recording doesn't work.
Errors are all this:
E 0:00:03:0139   input_callback: AudioUnitRender failed, code: -10863
  <C++ Source>   drivers/coreaudio/audio_driver_coreaudio.cpp:238 @ input_callback()

It has to do something with the AudioStreamMicrophone because if I remove that from the AudioStreamRecord node then the errors stop. Also if I turn the AudioStreamRecord node to not playing the errors stop. Tried manually creating a new mic resource and attaching that, got errors just the same. Also, the audio doesn't record and playback in addition to the errors.

**Screenshots of issue:**

![Screenshot of Godot](https://user-images.githubusercontent.com/85597948/228630732-6a2af4ba-cf22-48c9-ac74-96d15ca3cfaf.png)

**Comment by turnercore** [comment]
Thanks! That worked, but just for anyone that finds that after you need to change the Mix rate to 48000Hz in the Project Settings, not the script. (Although I also changed the default in the script as well).

**Comment by Calinou** [comment]
> Thanks! That worked, but just for anyone that finds that after you need to change the Mix rate to 48000Hz in the Project Settings, not the script. (Although I also changed the default in the script as well).

Does recording work if you change mix rate to 48000 Hz in the project settings, but keep the Mix rate option in the demo to 44100 Hz?
