### ISSUE TITLE
2D Navigation Demo Fails in Godot 4.0 

### ISSUE THREAD

**Issue by earsmeardius** [godotengine/godot-demo-projects#911]
**Which demo project is affected:**
2D Navigation Demo 3.5-9e68af3 when using Godot 4.0.

**OS/device including version:**
Windows 10 version 22H2

**Issue description:**
In navigation.gd, lines 62, 75, `path.remove(0)` should be `path.remove_at(0)`

In navigation.gd line 45, `NavigationServer2D.region_set_navpoly(region, navigation_poly)` should be `NavigationServer2D.region_set_navigation_polygon(region, navigation_poly)`

HTH.

**Comment by smix8** [comment]
Please provide a link to that demo cause the demo project name hints at this being an old Godot 3.5 version demo and no a demo made for Godot 4.0.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
