### ISSUE TITLE
Offset timer code doesn't work in Dodge the Creeps demo

### ISSUE THREAD

**Issue by RichAllen1976** [godotengine/godot-demo-projects#921]
**Which demo project is affected:**

**OS/device including version:**

**Issue description:**

**Screenshots of issue:**

**Comment by Calinou** [comment]
Can you describe this in detail? I don't understand what you mean.

**Comment by RichAllen1976** [comment]
[cid:357bb5a2-1e30-4f74-bbb4-e76c028408a5]

See above error message regarding the code.

I didn't write the code myself.

________________________________
