### ISSUE TITLE
Godot 4.0   godot-demo-projects-master\3d\ik   is not work  

### ISSUE THREAD

**Issue by masterjo** [godotengine/godot-demo-projects#946]
godot-demo-projects-master\3d\ik

3D Inverse Kinematics    is not work... ( godot 4.1.1 stable)

script error

**Comment by shashikant-panchal** [comment]
attempt  #946

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-demo-projects/issues/697, which tracks demos that need to be updated.
