### ISSUE TITLE
Should just be replacing all instances of ```ANDROID_SDK_ROOT``` with ```ANDROID_HOME``` if I'm not mistaken.

### ISSUE THREAD

**Issue by mizon1312** [godotengine/godot-demo-projects#948]
Should just be replacing all instances of ```ANDROID_SDK_ROOT``` with ```ANDROID_HOME``` if I'm not mistaken. 

Will open a pr upon confirmation.

_Originally posted by @philippesic in https://github.com/godotengine/godot/issues/80910#issuecomment-1689103320_

**Comment by Calinou** [comment]
Did you open this issue by accident? There are no references to this variable in the codebase of godot-demo-projects.
