### ISSUE TITLE
2D Hexagonal Map Demo broken on Godot 4.1

### ISSUE THREAD

**Issue by SkyeRise** [godotengine/godot-demo-projects#950]
**Which demo project is affected:**
2D Hexagonal Map Demo

**OS/device including version:**
Windows 11/64bit

**Issue description:**
Imported and the following happened (see screenshot):

**Screenshots of issue:**

![2dhexbugged](https://github.com/godotengine/godot-demo-projects/assets/16066754/6a1eb621-1b8b-4d3e-b58e-d9e0cc7bc59e)

**Comment by Calinou** [comment]
The demo looks correct to me on the `master` branch when using 4.2.dev4. Where did you download the demo from?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
