### ISSUE TITLE
Navigation Polygon 2D fails

### ISSUE THREAD

**Issue by matthewpetch** [godotengine/godot-demo-projects#951]
**Which demo project is affected:**
2d/navigation

**OS/device including version:**
Windows 10

**Issue description:**
Fails to run
Invalid call. Nonexistent function 'get_next_location' in base 'NavigationAgent2D'.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-demo-projects/issues/697 (the demo needs to be updated).
