### ISSUE TITLE
Velocity.x and y are outdated. (mono)

### ISSUE THREAD

**Issue by nviprod** [godotengine/godot-demo-projects#953]
**Which demo project is affected:**
Dodge The Creeps and other mono projects, like Pong.

**OS/device including version:**
Windows 11 Home

**Issue description:**
Putting in the code itself will give you a `'Vector2' does not contain a definition for 'y' ` error. Godot 4 requires you to capitalize the X and Y in `velocity.X` and `velocity.Y`

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-demo-projects/issues/697.
