### ISSUE TITLE
Parser Error: Function "update()" not found in base self. in Multitouch View

### ISSUE THREAD

**Issue by behroozbc** [godotengine/godot-demo-projects#959]
**Which demo project is affected:**
Multitouch View

**OS/device including version:**
Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated GeForce RTX 2060 () - Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz (20 Threads)
**Issue description:**
The project Multitouch View for mobile has called a method with the name of `update()` in the Main script line of 5 . However, the editor rise an error with this message `Parser Error: Function "update()" not found in base self. `. I found this method had been on version 3 which it renamed to `queue_redraw()` in version 4.

**Comment by Calinou** [comment]
- Fixed by https://github.com/godotengine/godot-demo-projects/pull/960.
