### ISSUE TITLE
Gui in 3D Demoproject no longer works

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot-demo-projects#979]
**Which demo project is affected:**
https://github.com/godotengine/godot-demo-projects/tree/master/viewport/gui_in_3d

**OS/device including version:**
Debian 12, X11, Xfce

**Issue description:**
The demo project "Gui in 3D" no longer works in v4.2-dev6.
Instead of the usual screen, only a gray background is displayed.

I would expect, that the demo project works and its content is shown.

Bisecting shows that it no longer works since https://github.com/godotengine/godot/pull/80813.

**Comment by GeorgeS2019** [comment]
We need a few more examples of 3D GUI, if possible, one that demonstrates 2D charts in 3D Gui

**Comment by GeorgeS2019** [comment]
Just realized [this ](https://github.com/MASSHUU12/godot-control-3d)could be relevant

**Comment by Alex2782** [comment]
Does this demo need to be ported?
The 3D camera is positioned incorrectly (animated)

![image](https://github.com/godotengine/godot-demo-projects/assets/41921395/b6110128-2816-4169-9814-a6bbfd9c9384)

**Comment by Alex2782** [comment]
This is how the animation looks in version 4.1.2.
In version 4.2 beta (1 and 2), the animation no longer works, always (0,0,0) position, behind the 2D GUI 

https://github.com/godotengine/godot-demo-projects/assets/41921395/a4f3df06-c676-42e5-b97f-b45151c8d5bc

**Comment by KoBeWi** [comment]
This looks like a regression in the engine.
