### ISSUE TITLE
Add texture resolution settings to the settings list

### ISSUE THREAD

**Issue by Cortrano** [godotengine/godot-demo-projects#981]
**Which demo project is affected:**
3d/graphics_settings

**Description:**
In my opinion, the demo with graphics settings lacks texture resolution settings. I don’t quite understand how this can be done and I didn’t really find anything on this topic in the documentation. It would be cool to see this setting implemented in a demo project

**Comment by Calinou** [comment]
Godot currently doesn't have a built-in way to reduce texture resolution, but there are 2 issues:

- What you probably want is [texture streaming](https://github.com/godotengine/godot-proposals/issues/3177) with a setting to limit the maximum memory pool size.
- Reducing texture size generally doesn't improve performance directly, unless you are running out of VRAM. This is uncommon in indie games given their tendency to use fewer, lower-resolution textures than modern AAA games.

**Comment by Cortrano** [comment]
> Reducing texture size generally doesn't improve performance directly, unless you are running out of VRAM. This is uncommon in indie games given their tendency to use fewer, lower-resolution textures than modern AAA games.

Then all that remains is to wait for the texture streaming option, and if it is added to godot, then add it to this template
