### ISSUE TITLE
Example of "webrtc_signaling" not working on the web

### ISSUE THREAD

**Issue by satoshidisciple** [godotengine/godot-demo-projects#983]
**Which demo project is affected:**

- https://github.com/godotengine/godot-demo-projects/tree/master/networking/webrtc_signaling

**OS/device including version:**
- Windows, Mac, Linux
- Browser: Google Chrome
- Godot version 4.1

**Issue description:**

To test, simply configure export for the Web. Run node_server and run the project.

When executed by the editor, everything will work normally,
but if you try to run it in the Browser the connection will not be established.

I investigated the problem and apparently the error is in performing "ws.get_ready_state" before "ws.pool" in the browser;

I created a PR fixing the bug: [https://github.com/godotengine/godot-demo-projects/pull/982](https://github.com/godotengine/godot-demo-projects/pull/982
)

**Comment by satoshidisciple** [comment]
My fix merge request was accepted, so I will close this issue. Thanks

**Comment by satoshidisciple** [comment]
My fix merge request was accepted, so I think you can now close this issue. Thank you

**Comment by aaronfranke** [comment]
@satoshidisciple Issues should not be closed until after the PR is merged. Also, you can ensure these things happen at the same time by adding "Fixes #983" in the PR description. I've went ahead and done this for you.
