### ISSUE TITLE
Update 2D Physics Platformer Demo (RigidBody) for Godot 4

### ISSUE THREAD

**Issue by picchio12** [godotengine/godot-demo-projects#991]
**Which demo project is affected:**
https://godotengine.org/asset-library/asset/119

**Description:**
The project is not compatible in Godot 4, even if converted (both full conversion and project.godot conversion)

**Comment by Calinou** [comment]
The demo in the `master` branch of this repository is up-to-date for Godot 4.

- See https://github.com/godotengine/godot-demo-projects/issues/920.
